package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BoletinadoColaborador generated by hbm2java
 */
public class BoletinadoColaborador implements java.io.Serializable {

	private Integer id;
	private int idColaboradorHistorial;
	private int tipoBoletinado;
	private Integer estatus;
	private Date fechaAlta;
	private String observaciones;

	public BoletinadoColaborador() {
	}

	public BoletinadoColaborador(int idColaboradorHistorial, int tipoBoletinado) {
		this.idColaboradorHistorial = idColaboradorHistorial;
		this.tipoBoletinado = tipoBoletinado;
	}

	public BoletinadoColaborador(int idColaboradorHistorial,
			int tipoBoletinado, Integer estatus, Date fechaAlta,
			String observaciones) {
		this.idColaboradorHistorial = idColaboradorHistorial;
		this.tipoBoletinado = tipoBoletinado;
		this.estatus = estatus;
		this.fechaAlta = fechaAlta;
		this.observaciones = observaciones;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdColaboradorHistorial() {
		return this.idColaboradorHistorial;
	}

	public void setIdColaboradorHistorial(int idColaboradorHistorial) {
		this.idColaboradorHistorial = idColaboradorHistorial;
	}

	public int getTipoBoletinado() {
		return this.tipoBoletinado;
	}

	public void setTipoBoletinado(int tipoBoletinado) {
		this.tipoBoletinado = tipoBoletinado;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
