package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * CatalogoMenu generated by hbm2java
 */
public class CatalogoMenu implements java.io.Serializable {

	private Integer id;
	private String modulo;
	private String etiqueta;
	private Integer idCatalogoSecciones;
	private String url;
	private Integer prioridad;

	public CatalogoMenu() {
	}

	public CatalogoMenu(String modulo, String etiqueta,
			Integer idCatalogoSecciones, String url, Integer prioridad) {
		this.modulo = modulo;
		this.etiqueta = etiqueta;
		this.idCatalogoSecciones = idCatalogoSecciones;
		this.url = url;
		this.prioridad = prioridad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	public Integer getIdCatalogoSecciones() {
		return this.idCatalogoSecciones;
	}

	public void setIdCatalogoSecciones(Integer idCatalogoSecciones) {
		this.idCatalogoSecciones = idCatalogoSecciones;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
