package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * CatalogoSecciones generated by hbm2java
 */
public class CatalogoSecciones implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String etiqueta;
	private Integer prioridad;

	public CatalogoSecciones() {
	}

	public CatalogoSecciones(String nombre, String etiqueta, Integer prioridad) {
		this.nombre = nombre;
		this.etiqueta = etiqueta;
		this.prioridad = prioridad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
