package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ColaboradorReferencia generated by hbm2java
 */
public class ColaboradorReferencia implements java.io.Serializable {

	private Integer id;
	private int idColaborador;
	private int idReferencia;

	public ColaboradorReferencia() {
	}

	public ColaboradorReferencia(int idColaborador, int idReferencia) {
		this.idColaborador = idColaborador;
		this.idReferencia = idReferencia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(int idColaborador) {
		this.idColaborador = idColaborador;
	}

	public int getIdReferencia() {
		return this.idReferencia;
	}

	public void setIdReferencia(int idReferencia) {
		this.idReferencia = idReferencia;
	}

}
