package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ColaboradoresHistorial generated by hbm2java
 */
public class ColaboradoresHistorial implements java.io.Serializable {

	private Integer id;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private Date fechaNacimiento;
	private String calle;
	private String numeroInterior;
	private String numeroExterior;
	private int idEstado;
	private int idMunicipio;
	private int idLocalidad;
	private String idCodigoPostal;
	private int idPromotor;
	private int tipo;
	private Integer idTipoColaborador;
	private String telefonoCasa;
	private String telefonoOficina;
	private String celular;
	private String correo;
	private Integer idReferencia;
	private String rfc;
	private Date fechaAlta;
	private int idUsuario;
	private Integer documentacionMinima;
	private int estatus;
	private String observaciones;
	private String numeroPersonal;
	private Integer idTipoContratacion;
	private Integer idTipoPersonal;
	private Integer replica;
	private Integer existe;
	private int colaboradorDesde;
	private String preregistro;
	private Integer idRegion;
	private String region;
	private Integer boletinado;
	private String extensionOficina;

	public ColaboradoresHistorial() {
	}

	public ColaboradoresHistorial(String nombres, String apellidoPaterno,
			String calle, String numeroExterior, int idEstado, int idMunicipio,
			int idLocalidad, String idCodigoPostal, int idPromotor, int tipo,
			String rfc, Date fechaAlta, int idUsuario, int estatus,
			String numeroPersonal, int colaboradorDesde) {
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idLocalidad = idLocalidad;
		this.idCodigoPostal = idCodigoPostal;
		this.idPromotor = idPromotor;
		this.tipo = tipo;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.estatus = estatus;
		this.numeroPersonal = numeroPersonal;
		this.colaboradorDesde = colaboradorDesde;
	}

	public ColaboradoresHistorial(String nombres, String apellidoPaterno,
			String apellidoMaterno, Date fechaNacimiento, String calle,
			String numeroInterior, String numeroExterior, int idEstado,
			int idMunicipio, int idLocalidad, String idCodigoPostal,
			int idPromotor, int tipo, Integer idTipoColaborador,
			String telefonoCasa, String telefonoOficina, String celular,
			String correo, Integer idReferencia, String rfc, Date fechaAlta,
			int idUsuario, Integer documentacionMinima, int estatus,
			String observaciones, String numeroPersonal,
			Integer idTipoContratacion, Integer idTipoPersonal,
			Integer replica, Integer existe, int colaboradorDesde,
			String preregistro, Integer idRegion, String region,
			Integer boletinado, String extensionOficina) {
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.fechaNacimiento = fechaNacimiento;
		this.calle = calle;
		this.numeroInterior = numeroInterior;
		this.numeroExterior = numeroExterior;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idLocalidad = idLocalidad;
		this.idCodigoPostal = idCodigoPostal;
		this.idPromotor = idPromotor;
		this.tipo = tipo;
		this.idTipoColaborador = idTipoColaborador;
		this.telefonoCasa = telefonoCasa;
		this.telefonoOficina = telefonoOficina;
		this.celular = celular;
		this.correo = correo;
		this.idReferencia = idReferencia;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.documentacionMinima = documentacionMinima;
		this.estatus = estatus;
		this.observaciones = observaciones;
		this.numeroPersonal = numeroPersonal;
		this.idTipoContratacion = idTipoContratacion;
		this.idTipoPersonal = idTipoPersonal;
		this.replica = replica;
		this.existe = existe;
		this.colaboradorDesde = colaboradorDesde;
		this.preregistro = preregistro;
		this.idRegion = idRegion;
		this.region = region;
		this.boletinado = boletinado;
		this.extensionOficina = extensionOficina;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public String getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(String idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	public int getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(int idPromotor) {
		this.idPromotor = idPromotor;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public Integer getIdTipoColaborador() {
		return this.idTipoColaborador;
	}

	public void setIdTipoColaborador(Integer idTipoColaborador) {
		this.idTipoColaborador = idTipoColaborador;
	}

	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		this.telefonoOficina = telefonoOficina;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Integer getIdReferencia() {
		return this.idReferencia;
	}

	public void setIdReferencia(Integer idReferencia) {
		this.idReferencia = idReferencia;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getDocumentacionMinima() {
		return this.documentacionMinima;
	}

	public void setDocumentacionMinima(Integer documentacionMinima) {
		this.documentacionMinima = documentacionMinima;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(String numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	public Integer getIdTipoContratacion() {
		return this.idTipoContratacion;
	}

	public void setIdTipoContratacion(Integer idTipoContratacion) {
		this.idTipoContratacion = idTipoContratacion;
	}

	public Integer getIdTipoPersonal() {
		return this.idTipoPersonal;
	}

	public void setIdTipoPersonal(Integer idTipoPersonal) {
		this.idTipoPersonal = idTipoPersonal;
	}

	public Integer getReplica() {
		return this.replica;
	}

	public void setReplica(Integer replica) {
		this.replica = replica;
	}

	public Integer getExiste() {
		return this.existe;
	}

	public void setExiste(Integer existe) {
		this.existe = existe;
	}

	public int getColaboradorDesde() {
		return this.colaboradorDesde;
	}

	public void setColaboradorDesde(int colaboradorDesde) {
		this.colaboradorDesde = colaboradorDesde;
	}

	public String getPreregistro() {
		return this.preregistro;
	}

	public void setPreregistro(String preregistro) {
		this.preregistro = preregistro;
	}

	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public Integer getBoletinado() {
		return this.boletinado;
	}

	public void setBoletinado(Integer boletinado) {
		this.boletinado = boletinado;
	}

	public String getExtensionOficina() {
		return this.extensionOficina;
	}

	public void setExtensionOficina(String extensionOficina) {
		this.extensionOficina = extensionOficina;
	}

}
