package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CompradoresNomina generated by hbm2java
 */
public class CompradoresNomina implements java.io.Serializable {

	private Integer id;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String rfc;
	private Integer numeroPersonal;
	private Integer idTipoContratacion;
	private Integer idTipoPersonal;
	private int tipoComprador;
	private Integer idSector;
	private Integer programa;
	private int idRegion;
	private Date fechaRegistro;
	private int idUsuario;

	public CompradoresNomina() {
	}

	public CompradoresNomina(String nombres, String apellidoPaterno,
			int tipoComprador, int idRegion, Date fechaRegistro, int idUsuario) {
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.tipoComprador = tipoComprador;
		this.idRegion = idRegion;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public CompradoresNomina(String nombres, String apellidoPaterno,
			String apellidoMaterno, String rfc, Integer numeroPersonal,
			Integer idTipoContratacion, Integer idTipoPersonal,
			int tipoComprador, Integer idSector, Integer programa,
			int idRegion, Date fechaRegistro, int idUsuario) {
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.rfc = rfc;
		this.numeroPersonal = numeroPersonal;
		this.idTipoContratacion = idTipoContratacion;
		this.idTipoPersonal = idTipoPersonal;
		this.tipoComprador = tipoComprador;
		this.idSector = idSector;
		this.programa = programa;
		this.idRegion = idRegion;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Integer getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(Integer numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	public Integer getIdTipoContratacion() {
		return this.idTipoContratacion;
	}

	public void setIdTipoContratacion(Integer idTipoContratacion) {
		this.idTipoContratacion = idTipoContratacion;
	}

	public Integer getIdTipoPersonal() {
		return this.idTipoPersonal;
	}

	public void setIdTipoPersonal(Integer idTipoPersonal) {
		this.idTipoPersonal = idTipoPersonal;
	}

	public int getTipoComprador() {
		return this.tipoComprador;
	}

	public void setTipoComprador(int tipoComprador) {
		this.tipoComprador = tipoComprador;
	}

	public Integer getIdSector() {
		return this.idSector;
	}

	public void setIdSector(Integer idSector) {
		this.idSector = idSector;
	}

	public Integer getPrograma() {
		return this.programa;
	}

	public void setPrograma(Integer programa) {
		this.programa = programa;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
