package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * DatosColaboradorMaestro generated by hbm2java
 */
public class DatosColaboradorMaestro implements java.io.Serializable {

	private DatosColaboradorMaestroId id;

	public DatosColaboradorMaestro() {
	}

	public DatosColaboradorMaestro(DatosColaboradorMaestroId id) {
		this.id = id;
	}

	public DatosColaboradorMaestroId getId() {
		return this.id;
	}

	public void setId(DatosColaboradorMaestroId id) {
		this.id = id;
	}

}
