package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * DatosFc2colaboradorId generated by hbm2java
 */
public class DatosFc2colaboradorId implements java.io.Serializable {

	private int id;
	private int idPromotor;
	private String nombre;
	private String rfc;
	private Date fechaNacimiento;
	private String correo;
	private String direccion;
	private String telefonoCasa;
	private String celular;
	private String referencia;

	public DatosFc2colaboradorId() {
	}

	public DatosFc2colaboradorId(int id, int idPromotor, String rfc,
			String correo, String direccion, String telefonoCasa, String celular) {
		this.id = id;
		this.idPromotor = idPromotor;
		this.rfc = rfc;
		this.correo = correo;
		this.direccion = direccion;
		this.telefonoCasa = telefonoCasa;
		this.celular = celular;
	}

	public DatosFc2colaboradorId(int id, int idPromotor, String nombre,
			String rfc, Date fechaNacimiento, String correo, String direccion,
			String telefonoCasa, String celular, String referencia) {
		this.id = id;
		this.idPromotor = idPromotor;
		this.nombre = nombre;
		this.rfc = rfc;
		this.fechaNacimiento = fechaNacimiento;
		this.correo = correo;
		this.direccion = direccion;
		this.telefonoCasa = telefonoCasa;
		this.celular = celular;
		this.referencia = referencia;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(int idPromotor) {
		this.idPromotor = idPromotor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatosFc2colaboradorId))
			return false;
		DatosFc2colaboradorId castOther = (DatosFc2colaboradorId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdPromotor() == castOther.getIdPromotor())
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getRfc() == castOther.getRfc()) || (this.getRfc() != null
						&& castOther.getRfc() != null && this.getRfc().equals(
						castOther.getRfc())))
				&& ((this.getFechaNacimiento() == castOther
						.getFechaNacimiento()) || (this.getFechaNacimiento() != null
						&& castOther.getFechaNacimiento() != null && this
						.getFechaNacimiento().equals(
								castOther.getFechaNacimiento())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this
						.getDireccion() != null
						&& castOther.getDireccion() != null && this
						.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getTelefonoCasa() == castOther.getTelefonoCasa()) || (this
						.getTelefonoCasa() != null
						&& castOther.getTelefonoCasa() != null && this
						.getTelefonoCasa().equals(castOther.getTelefonoCasa())))
				&& ((this.getCelular() == castOther.getCelular()) || (this
						.getCelular() != null && castOther.getCelular() != null && this
						.getCelular().equals(castOther.getCelular())))
				&& ((this.getReferencia() == castOther.getReferencia()) || (this
						.getReferencia() != null
						&& castOther.getReferencia() != null && this
						.getReferencia().equals(castOther.getReferencia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdPromotor();
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getRfc() == null ? 0 : this.getRfc().hashCode());
		result = 37
				* result
				+ (getFechaNacimiento() == null ? 0 : this.getFechaNacimiento()
						.hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result
				+ (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37
				* result
				+ (getTelefonoCasa() == null ? 0 : this.getTelefonoCasa()
						.hashCode());
		result = 37 * result
				+ (getCelular() == null ? 0 : this.getCelular().hashCode());
		result = 37
				* result
				+ (getReferencia() == null ? 0 : this.getReferencia()
						.hashCode());
		return result;
	}

}
