package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * DatosFc2colaborador generated by hbm2java
 */
public class DatosFc2colaborador implements java.io.Serializable {

	private DatosFc2colaboradorId id;

	public DatosFc2colaborador() {
	}

	public DatosFc2colaborador(DatosFc2colaboradorId id) {
		this.id = id;
	}

	public DatosFc2colaboradorId getId() {
		return this.id;
	}

	public void setId(DatosFc2colaboradorId id) {
		this.id = id;
	}

}
