package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Deudores generated by hbm2java
 */
public class Deudores implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String rfc;
	private float monto;
	private int referencia;

	public Deudores() {
	}

	public Deudores(String nombre, String rfc, float monto, int referencia) {
		this.nombre = nombre;
		this.rfc = rfc;
		this.monto = monto;
		this.referencia = referencia;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public float getMonto() {
		return this.monto;
	}

	public void setMonto(float monto) {
		this.monto = monto;
	}

	public int getReferencia() {
		return this.referencia;
	}

	public void setReferencia(int referencia) {
		this.referencia = referencia;
	}

}
