package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Dpn generated by hbm2java
 */
public class Dpn implements java.io.Serializable {

	private Integer iddpn;
	private Float cantidad;
	private String numreferencia;
	private Date fechaaplicacion;
	private Integer estatus;
	private String observaciones;
	private Integer idquincena;
	private Integer idusuario;

	public Dpn() {
	}

	public Dpn(Float cantidad, String numreferencia, Date fechaaplicacion,
			Integer estatus, String observaciones, Integer idquincena,
			Integer idusuario) {
		this.cantidad = cantidad;
		this.numreferencia = numreferencia;
		this.fechaaplicacion = fechaaplicacion;
		this.estatus = estatus;
		this.observaciones = observaciones;
		this.idquincena = idquincena;
		this.idusuario = idusuario;
	}

	public Integer getIddpn() {
		return this.iddpn;
	}

	public void setIddpn(Integer iddpn) {
		this.iddpn = iddpn;
	}

	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	public String getNumreferencia() {
		return this.numreferencia;
	}

	public void setNumreferencia(String numreferencia) {
		this.numreferencia = numreferencia;
	}

	public Date getFechaaplicacion() {
		return this.fechaaplicacion;
	}

	public void setFechaaplicacion(Date fechaaplicacion) {
		this.fechaaplicacion = fechaaplicacion;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getIdquincena() {
		return this.idquincena;
	}

	public void setIdquincena(Integer idquincena) {
		this.idquincena = idquincena;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

}
