package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * EfectividadAcd generated by hbm2java
 */
public class EfectividadAcd implements java.io.Serializable {

	private EfectividadAcdId id;

	public EfectividadAcd() {
	}

	public EfectividadAcd(EfectividadAcdId id) {
		this.id = id;
	}

	public EfectividadAcdId getId() {
		return this.id;
	}

	public void setId(EfectividadAcdId id) {
		this.id = id;
	}

}
