package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private Integer id;
	private String nombres;
	private int idPuesto;
	private int usuarioAsignado;

	public Empleados() {
	}

	public Empleados(String nombres, int idPuesto, int usuarioAsignado) {
		this.nombres = nombres;
		this.idPuesto = idPuesto;
		this.usuarioAsignado = usuarioAsignado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public int getIdPuesto() {
		return this.idPuesto;
	}

	public void setIdPuesto(int idPuesto) {
		this.idPuesto = idPuesto;
	}

	public int getUsuarioAsignado() {
		return this.usuarioAsignado;
	}

	public void setUsuarioAsignado(int usuarioAsignado) {
		this.usuarioAsignado = usuarioAsignado;
	}

}
