package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Enlaces2014 generated by hbm2java
 */
public class Enlaces2014 implements java.io.Serializable {

	private Enlaces2014Id id;

	public Enlaces2014() {
	}

	public Enlaces2014(Enlaces2014Id id) {
		this.id = id;
	}

	public Enlaces2014Id getId() {
		return this.id;
	}

	public void setId(Enlaces2014Id id) {
		this.id = id;
	}

}
