package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Estados generated by hbm2java
 */
public class Estados implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int estado;

	public Estados() {
	}

	public Estados(String nombre, int estado) {
		this.nombre = nombre;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}

}
