package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Fc1 generated by hbm2java
 */
public class Fc1 implements java.io.Serializable {

	private Integer id;
	private String folio;
	private int idPromotor;
	private Date fechaEntrega;
	private Date fechaAlta;
	private int idUsuario;

	public Fc1() {
	}

	public Fc1(String folio, int idPromotor, Date fechaEntrega, Date fechaAlta,
			int idUsuario) {
		this.folio = folio;
		this.idPromotor = idPromotor;
		this.fechaEntrega = fechaEntrega;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public int getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(int idPromotor) {
		this.idPromotor = idPromotor;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
