package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc1bBoletos generated by hbm2java
 */
public class Fc1bBoletos implements java.io.Serializable {

	private Integer id;
	private Integer idFc1bCarteras;
	private Integer idBoleto;

	public Fc1bBoletos() {
	}

	public Fc1bBoletos(Integer idFc1bCarteras, Integer idBoleto) {
		this.idFc1bCarteras = idFc1bCarteras;
		this.idBoleto = idBoleto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdFc1bCarteras() {
		return this.idFc1bCarteras;
	}

	public void setIdFc1bCarteras(Integer idFc1bCarteras) {
		this.idFc1bCarteras = idFc1bCarteras;
	}

	public Integer getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(Integer idBoleto) {
		this.idBoleto = idBoleto;
	}

}
