package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc1Carteras generated by hbm2java
 */
public class Fc1Carteras implements java.io.Serializable {

	private Integer id;
	private int idFc1;
	private int idCartera;
	private int asignado;

	public Fc1Carteras() {
	}

	public Fc1Carteras(int idFc1, int idCartera, int asignado) {
		this.idFc1 = idFc1;
		this.idCartera = idCartera;
		this.asignado = asignado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdFc1() {
		return this.idFc1;
	}

	public void setIdFc1(int idFc1) {
		this.idFc1 = idFc1;
	}

	public int getIdCartera() {
		return this.idCartera;
	}

	public void setIdCartera(int idCartera) {
		this.idCartera = idCartera;
	}

	public int getAsignado() {
		return this.asignado;
	}

	public void setAsignado(int asignado) {
		this.asignado = asignado;
	}

}
