package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Fc2 generated by hbm2java
 */
public class Fc2 implements java.io.Serializable {

	private Integer id;
	private int idFormato;
	private int idColaborador;
	private int monto;
	private Date fecha;
	private int tipoSector;
	private int idTipoColaborador;
	private int sectorExterno;
	private int idSector;
	private int idRegion;
	private String carrera;
	private String area;
	private String localidad;
	private int nomina;
	private int trinet;
	private Date fechaAlta;
	private int idUsuario;
	private int comision;
	private int tipo;
	private String codigo;
	private String folioCita;
	private Integer tipoContacto;

	public Fc2() {
	}

	public Fc2(int idFormato, int idColaborador, int monto, Date fecha,
			int tipoSector, int idTipoColaborador, int sectorExterno,
			int idSector, int idRegion, int nomina, int trinet, Date fechaAlta,
			int idUsuario, int comision, int tipo) {
		this.idFormato = idFormato;
		this.idColaborador = idColaborador;
		this.monto = monto;
		this.fecha = fecha;
		this.tipoSector = tipoSector;
		this.idTipoColaborador = idTipoColaborador;
		this.sectorExterno = sectorExterno;
		this.idSector = idSector;
		this.idRegion = idRegion;
		this.nomina = nomina;
		this.trinet = trinet;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.comision = comision;
		this.tipo = tipo;
	}

	public Fc2(int idFormato, int idColaborador, int monto, Date fecha,
			int tipoSector, int idTipoColaborador, int sectorExterno,
			int idSector, int idRegion, String carrera, String area,
			String localidad, int nomina, int trinet, Date fechaAlta,
			int idUsuario, int comision, int tipo, String codigo,
			String folioCita, Integer tipoContacto) {
		this.idFormato = idFormato;
		this.idColaborador = idColaborador;
		this.monto = monto;
		this.fecha = fecha;
		this.tipoSector = tipoSector;
		this.idTipoColaborador = idTipoColaborador;
		this.sectorExterno = sectorExterno;
		this.idSector = idSector;
		this.idRegion = idRegion;
		this.carrera = carrera;
		this.area = area;
		this.localidad = localidad;
		this.nomina = nomina;
		this.trinet = trinet;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.comision = comision;
		this.tipo = tipo;
		this.codigo = codigo;
		this.folioCita = folioCita;
		this.tipoContacto = tipoContacto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdFormato() {
		return this.idFormato;
	}

	public void setIdFormato(int idFormato) {
		this.idFormato = idFormato;
	}

	public int getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(int idColaborador) {
		this.idColaborador = idColaborador;
	}

	public int getMonto() {
		return this.monto;
	}

	public void setMonto(int monto) {
		this.monto = monto;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getTipoSector() {
		return this.tipoSector;
	}

	public void setTipoSector(int tipoSector) {
		this.tipoSector = tipoSector;
	}

	public int getIdTipoColaborador() {
		return this.idTipoColaborador;
	}

	public void setIdTipoColaborador(int idTipoColaborador) {
		this.idTipoColaborador = idTipoColaborador;
	}

	public int getSectorExterno() {
		return this.sectorExterno;
	}

	public void setSectorExterno(int sectorExterno) {
		this.sectorExterno = sectorExterno;
	}

	public int getIdSector() {
		return this.idSector;
	}

	public void setIdSector(int idSector) {
		this.idSector = idSector;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public String getCarrera() {
		return this.carrera;
	}

	public void setCarrera(String carrera) {
		this.carrera = carrera;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public int getNomina() {
		return this.nomina;
	}

	public void setNomina(int nomina) {
		this.nomina = nomina;
	}

	public int getTrinet() {
		return this.trinet;
	}

	public void setTrinet(int trinet) {
		this.trinet = trinet;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getComision() {
		return this.comision;
	}

	public void setComision(int comision) {
		this.comision = comision;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getFolioCita() {
		return this.folioCita;
	}

	public void setFolioCita(String folioCita) {
		this.folioCita = folioCita;
	}

	public Integer getTipoContacto() {
		return this.tipoContacto;
	}

	public void setTipoContacto(Integer tipoContacto) {
		this.tipoContacto = tipoContacto;
	}

}
