package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc2Boletos generated by hbm2java
 */
public class Fc2Boletos implements java.io.Serializable {

	private Integer id;
	private int idFc2Cartera;
	private int idBoleto;
	private int nomina;

	public Fc2Boletos() {
	}

	public Fc2Boletos(int idFc2Cartera, int idBoleto, int nomina) {
		this.idFc2Cartera = idFc2Cartera;
		this.idBoleto = idBoleto;
		this.nomina = nomina;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdFc2Cartera() {
		return this.idFc2Cartera;
	}

	public void setIdFc2Cartera(int idFc2Cartera) {
		this.idFc2Cartera = idFc2Cartera;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

	public int getNomina() {
		return this.nomina;
	}

	public void setNomina(int nomina) {
		this.nomina = nomina;
	}

}
