package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Fc6 generated by hbm2java
 */
public class Fc6 implements java.io.Serializable {

	private Integer id;
	private int idColaborador;
	private int idTipoIncidencia;
	private int idCartera;
	private String actaMinisterio;
	private String comentario;
	private Date fechaRegistro;
	private int idUsuario;

	public Fc6() {
	}

	public Fc6(int idColaborador, int idTipoIncidencia, int idCartera,
			String actaMinisterio, Date fechaRegistro, int idUsuario) {
		this.idColaborador = idColaborador;
		this.idTipoIncidencia = idTipoIncidencia;
		this.idCartera = idCartera;
		this.actaMinisterio = actaMinisterio;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public Fc6(int idColaborador, int idTipoIncidencia, int idCartera,
			String actaMinisterio, String comentario, Date fechaRegistro,
			int idUsuario) {
		this.idColaborador = idColaborador;
		this.idTipoIncidencia = idTipoIncidencia;
		this.idCartera = idCartera;
		this.actaMinisterio = actaMinisterio;
		this.comentario = comentario;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(int idColaborador) {
		this.idColaborador = idColaborador;
	}

	public int getIdTipoIncidencia() {
		return this.idTipoIncidencia;
	}

	public void setIdTipoIncidencia(int idTipoIncidencia) {
		this.idTipoIncidencia = idTipoIncidencia;
	}

	public int getIdCartera() {
		return this.idCartera;
	}

	public void setIdCartera(int idCartera) {
		this.idCartera = idCartera;
	}

	public String getActaMinisterio() {
		return this.actaMinisterio;
	}

	public void setActaMinisterio(String actaMinisterio) {
		this.actaMinisterio = actaMinisterio;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
