package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc7Boletos generated by hbm2java
 */
public class Fc7Boletos implements java.io.Serializable {

	private Integer id;
	private Integer idFc7Carteras;
	private Integer idBoleto;

	public Fc7Boletos() {
	}

	public Fc7Boletos(Integer idFc7Carteras, Integer idBoleto) {
		this.idFc7Carteras = idFc7Carteras;
		this.idBoleto = idBoleto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdFc7Carteras() {
		return this.idFc7Carteras;
	}

	public void setIdFc7Carteras(Integer idFc7Carteras) {
		this.idFc7Carteras = idFc7Carteras;
	}

	public Integer getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(Integer idBoleto) {
		this.idBoleto = idBoleto;
	}

}
