package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * KardexCartera generated by hbm2java
 */
public class KardexCartera implements java.io.Serializable {

	private Integer id;
	private int idAlmacen;
	private int entrada;
	private int salida;
	private Date fecha;
	private int idMovimiento;
	private int idCartera;

	public KardexCartera() {
	}

	public KardexCartera(int idAlmacen, int entrada, int salida, Date fecha,
			int idMovimiento, int idCartera) {
		this.idAlmacen = idAlmacen;
		this.entrada = entrada;
		this.salida = salida;
		this.fecha = fecha;
		this.idMovimiento = idMovimiento;
		this.idCartera = idCartera;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdAlmacen() {
		return this.idAlmacen;
	}

	public void setIdAlmacen(int idAlmacen) {
		this.idAlmacen = idAlmacen;
	}

	public int getEntrada() {
		return this.entrada;
	}

	public void setEntrada(int entrada) {
		this.entrada = entrada;
	}

	public int getSalida() {
		return this.salida;
	}

	public void setSalida(int salida) {
		this.salida = salida;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getIdMovimiento() {
		return this.idMovimiento;
	}

	public void setIdMovimiento(int idMovimiento) {
		this.idMovimiento = idMovimiento;
	}

	public int getIdCartera() {
		return this.idCartera;
	}

	public void setIdCartera(int idCartera) {
		this.idCartera = idCartera;
	}

}
