package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * MaestroColaboradorLocalId generated by hbm2java
 */
public class MaestroColaboradorLocalId implements java.io.Serializable {

	private int id;
	private String referencia;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private Integer comision;
	private String promotor;
	private String telefonoCasa;
	private String celular;
	private String correo;
	private String calle;
	private String numeroExterior;
	private String numeroInterior;
	private String colonia;
	private String ciudad;
	private String estado;
	private Integer replica;
	private Integer cp;
	private String sector;
	private Integer talonarios;
	private Integer boletos;
	private Integer fc3;
	private Integer fc4;
	private Integer fc4b;
	private Integer fc4bVendido;
	private Integer boletosVendidos;
	private Integer monto;
	private Integer abonoDevolucion;
	private Integer nominas;
	private Integer nominasFuv;
	private Integer dpnNetos;
	private Integer pagosNeto;
	private Double saldos;
	private String estatusPago;
	private String estatusCarteras;
	private String tipoColaborador;
	private Integer boletosElectronicos;
	private String region;

	public MaestroColaboradorLocalId() {
	}

	public MaestroColaboradorLocalId(int id) {
		this.id = id;
	}

	public MaestroColaboradorLocalId(int id, String referencia, String nombres,
			String apellidoPaterno, String apellidoMaterno, Integer comision,
			String promotor, String telefonoCasa, String celular,
			String correo, String calle, String numeroExterior,
			String numeroInterior, String colonia, String ciudad,
			String estado, Integer replica, Integer cp, String sector,
			Integer talonarios, Integer boletos, Integer fc3, Integer fc4,
			Integer fc4b, Integer fc4bVendido, Integer boletosVendidos,
			Integer monto, Integer abonoDevolucion, Integer nominas,
			Integer nominasFuv, Integer dpnNetos, Integer pagosNeto,
			Double saldos, String estatusPago, String estatusCarteras,
			String tipoColaborador, Integer boletosElectronicos, String region) {
		this.id = id;
		this.referencia = referencia;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.comision = comision;
		this.promotor = promotor;
		this.telefonoCasa = telefonoCasa;
		this.celular = celular;
		this.correo = correo;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.numeroInterior = numeroInterior;
		this.colonia = colonia;
		this.ciudad = ciudad;
		this.estado = estado;
		this.replica = replica;
		this.cp = cp;
		this.sector = sector;
		this.talonarios = talonarios;
		this.boletos = boletos;
		this.fc3 = fc3;
		this.fc4 = fc4;
		this.fc4b = fc4b;
		this.fc4bVendido = fc4bVendido;
		this.boletosVendidos = boletosVendidos;
		this.monto = monto;
		this.abonoDevolucion = abonoDevolucion;
		this.nominas = nominas;
		this.nominasFuv = nominasFuv;
		this.dpnNetos = dpnNetos;
		this.pagosNeto = pagosNeto;
		this.saldos = saldos;
		this.estatusPago = estatusPago;
		this.estatusCarteras = estatusCarteras;
		this.tipoColaborador = tipoColaborador;
		this.boletosElectronicos = boletosElectronicos;
		this.region = region;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public Integer getComision() {
		return this.comision;
	}

	public void setComision(Integer comision) {
		this.comision = comision;
	}

	public String getPromotor() {
		return this.promotor;
	}

	public void setPromotor(String promotor) {
		this.promotor = promotor;
	}

	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getReplica() {
		return this.replica;
	}

	public void setReplica(Integer replica) {
		this.replica = replica;
	}

	public Integer getCp() {
		return this.cp;
	}

	public void setCp(Integer cp) {
		this.cp = cp;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public Integer getTalonarios() {
		return this.talonarios;
	}

	public void setTalonarios(Integer talonarios) {
		this.talonarios = talonarios;
	}

	public Integer getBoletos() {
		return this.boletos;
	}

	public void setBoletos(Integer boletos) {
		this.boletos = boletos;
	}

	public Integer getFc3() {
		return this.fc3;
	}

	public void setFc3(Integer fc3) {
		this.fc3 = fc3;
	}

	public Integer getFc4() {
		return this.fc4;
	}

	public void setFc4(Integer fc4) {
		this.fc4 = fc4;
	}

	public Integer getFc4b() {
		return this.fc4b;
	}

	public void setFc4b(Integer fc4b) {
		this.fc4b = fc4b;
	}

	public Integer getFc4bVendido() {
		return this.fc4bVendido;
	}

	public void setFc4bVendido(Integer fc4bVendido) {
		this.fc4bVendido = fc4bVendido;
	}

	public Integer getBoletosVendidos() {
		return this.boletosVendidos;
	}

	public void setBoletosVendidos(Integer boletosVendidos) {
		this.boletosVendidos = boletosVendidos;
	}

	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	public Integer getAbonoDevolucion() {
		return this.abonoDevolucion;
	}

	public void setAbonoDevolucion(Integer abonoDevolucion) {
		this.abonoDevolucion = abonoDevolucion;
	}

	public Integer getNominas() {
		return this.nominas;
	}

	public void setNominas(Integer nominas) {
		this.nominas = nominas;
	}

	public Integer getNominasFuv() {
		return this.nominasFuv;
	}

	public void setNominasFuv(Integer nominasFuv) {
		this.nominasFuv = nominasFuv;
	}

	public Integer getDpnNetos() {
		return this.dpnNetos;
	}

	public void setDpnNetos(Integer dpnNetos) {
		this.dpnNetos = dpnNetos;
	}

	public Integer getPagosNeto() {
		return this.pagosNeto;
	}

	public void setPagosNeto(Integer pagosNeto) {
		this.pagosNeto = pagosNeto;
	}

	public Double getSaldos() {
		return this.saldos;
	}

	public void setSaldos(Double saldos) {
		this.saldos = saldos;
	}

	public String getEstatusPago() {
		return this.estatusPago;
	}

	public void setEstatusPago(String estatusPago) {
		this.estatusPago = estatusPago;
	}

	public String getEstatusCarteras() {
		return this.estatusCarteras;
	}

	public void setEstatusCarteras(String estatusCarteras) {
		this.estatusCarteras = estatusCarteras;
	}

	public String getTipoColaborador() {
		return this.tipoColaborador;
	}

	public void setTipoColaborador(String tipoColaborador) {
		this.tipoColaborador = tipoColaborador;
	}

	public Integer getBoletosElectronicos() {
		return this.boletosElectronicos;
	}

	public void setBoletosElectronicos(Integer boletosElectronicos) {
		this.boletosElectronicos = boletosElectronicos;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaestroColaboradorLocalId))
			return false;
		MaestroColaboradorLocalId castOther = (MaestroColaboradorLocalId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getReferencia() == castOther.getReferencia()) || (this
						.getReferencia() != null
						&& castOther.getReferencia() != null && this
						.getReferencia().equals(castOther.getReferencia())))
				&& ((this.getNombres() == castOther.getNombres()) || (this
						.getNombres() != null && castOther.getNombres() != null && this
						.getNombres().equals(castOther.getNombres())))
				&& ((this.getApellidoPaterno() == castOther
						.getApellidoPaterno()) || (this.getApellidoPaterno() != null
						&& castOther.getApellidoPaterno() != null && this
						.getApellidoPaterno().equals(
								castOther.getApellidoPaterno())))
				&& ((this.getApellidoMaterno() == castOther
						.getApellidoMaterno()) || (this.getApellidoMaterno() != null
						&& castOther.getApellidoMaterno() != null && this
						.getApellidoMaterno().equals(
								castOther.getApellidoMaterno())))
				&& ((this.getComision() == castOther.getComision()) || (this
						.getComision() != null
						&& castOther.getComision() != null && this
						.getComision().equals(castOther.getComision())))
				&& ((this.getPromotor() == castOther.getPromotor()) || (this
						.getPromotor() != null
						&& castOther.getPromotor() != null && this
						.getPromotor().equals(castOther.getPromotor())))
				&& ((this.getTelefonoCasa() == castOther.getTelefonoCasa()) || (this
						.getTelefonoCasa() != null
						&& castOther.getTelefonoCasa() != null && this
						.getTelefonoCasa().equals(castOther.getTelefonoCasa())))
				&& ((this.getCelular() == castOther.getCelular()) || (this
						.getCelular() != null && castOther.getCelular() != null && this
						.getCelular().equals(castOther.getCelular())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getCalle() == castOther.getCalle()) || (this
						.getCalle() != null && castOther.getCalle() != null && this
						.getCalle().equals(castOther.getCalle())))
				&& ((this.getNumeroExterior() == castOther.getNumeroExterior()) || (this
						.getNumeroExterior() != null
						&& castOther.getNumeroExterior() != null && this
						.getNumeroExterior().equals(
								castOther.getNumeroExterior())))
				&& ((this.getNumeroInterior() == castOther.getNumeroInterior()) || (this
						.getNumeroInterior() != null
						&& castOther.getNumeroInterior() != null && this
						.getNumeroInterior().equals(
								castOther.getNumeroInterior())))
				&& ((this.getColonia() == castOther.getColonia()) || (this
						.getColonia() != null && castOther.getColonia() != null && this
						.getColonia().equals(castOther.getColonia())))
				&& ((this.getCiudad() == castOther.getCiudad()) || (this
						.getCiudad() != null && castOther.getCiudad() != null && this
						.getCiudad().equals(castOther.getCiudad())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getReplica() == castOther.getReplica()) || (this
						.getReplica() != null && castOther.getReplica() != null && this
						.getReplica().equals(castOther.getReplica())))
				&& ((this.getCp() == castOther.getCp()) || (this.getCp() != null
						&& castOther.getCp() != null && this.getCp().equals(
						castOther.getCp())))
				&& ((this.getSector() == castOther.getSector()) || (this
						.getSector() != null && castOther.getSector() != null && this
						.getSector().equals(castOther.getSector())))
				&& ((this.getTalonarios() == castOther.getTalonarios()) || (this
						.getTalonarios() != null
						&& castOther.getTalonarios() != null && this
						.getTalonarios().equals(castOther.getTalonarios())))
				&& ((this.getBoletos() == castOther.getBoletos()) || (this
						.getBoletos() != null && castOther.getBoletos() != null && this
						.getBoletos().equals(castOther.getBoletos())))
				&& ((this.getFc3() == castOther.getFc3()) || (this.getFc3() != null
						&& castOther.getFc3() != null && this.getFc3().equals(
						castOther.getFc3())))
				&& ((this.getFc4() == castOther.getFc4()) || (this.getFc4() != null
						&& castOther.getFc4() != null && this.getFc4().equals(
						castOther.getFc4())))
				&& ((this.getFc4b() == castOther.getFc4b()) || (this.getFc4b() != null
						&& castOther.getFc4b() != null && this.getFc4b()
						.equals(castOther.getFc4b())))
				&& ((this.getFc4bVendido() == castOther.getFc4bVendido()) || (this
						.getFc4bVendido() != null
						&& castOther.getFc4bVendido() != null && this
						.getFc4bVendido().equals(castOther.getFc4bVendido())))
				&& ((this.getBoletosVendidos() == castOther
						.getBoletosVendidos()) || (this.getBoletosVendidos() != null
						&& castOther.getBoletosVendidos() != null && this
						.getBoletosVendidos().equals(
								castOther.getBoletosVendidos())))
				&& ((this.getMonto() == castOther.getMonto()) || (this
						.getMonto() != null && castOther.getMonto() != null && this
						.getMonto().equals(castOther.getMonto())))
				&& ((this.getAbonoDevolucion() == castOther
						.getAbonoDevolucion()) || (this.getAbonoDevolucion() != null
						&& castOther.getAbonoDevolucion() != null && this
						.getAbonoDevolucion().equals(
								castOther.getAbonoDevolucion())))
				&& ((this.getNominas() == castOther.getNominas()) || (this
						.getNominas() != null && castOther.getNominas() != null && this
						.getNominas().equals(castOther.getNominas())))
				&& ((this.getNominasFuv() == castOther.getNominasFuv()) || (this
						.getNominasFuv() != null
						&& castOther.getNominasFuv() != null && this
						.getNominasFuv().equals(castOther.getNominasFuv())))
				&& ((this.getDpnNetos() == castOther.getDpnNetos()) || (this
						.getDpnNetos() != null
						&& castOther.getDpnNetos() != null && this
						.getDpnNetos().equals(castOther.getDpnNetos())))
				&& ((this.getPagosNeto() == castOther.getPagosNeto()) || (this
						.getPagosNeto() != null
						&& castOther.getPagosNeto() != null && this
						.getPagosNeto().equals(castOther.getPagosNeto())))
				&& ((this.getSaldos() == castOther.getSaldos()) || (this
						.getSaldos() != null && castOther.getSaldos() != null && this
						.getSaldos().equals(castOther.getSaldos())))
				&& ((this.getEstatusPago() == castOther.getEstatusPago()) || (this
						.getEstatusPago() != null
						&& castOther.getEstatusPago() != null && this
						.getEstatusPago().equals(castOther.getEstatusPago())))
				&& ((this.getEstatusCarteras() == castOther
						.getEstatusCarteras()) || (this.getEstatusCarteras() != null
						&& castOther.getEstatusCarteras() != null && this
						.getEstatusCarteras().equals(
								castOther.getEstatusCarteras())))
				&& ((this.getTipoColaborador() == castOther
						.getTipoColaborador()) || (this.getTipoColaborador() != null
						&& castOther.getTipoColaborador() != null && this
						.getTipoColaborador().equals(
								castOther.getTipoColaborador())))
				&& ((this.getBoletosElectronicos() == castOther
						.getBoletosElectronicos()) || (this
						.getBoletosElectronicos() != null
						&& castOther.getBoletosElectronicos() != null && this
						.getBoletosElectronicos().equals(
								castOther.getBoletosElectronicos())))
				&& ((this.getRegion() == castOther.getRegion()) || (this
						.getRegion() != null && castOther.getRegion() != null && this
						.getRegion().equals(castOther.getRegion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getReferencia() == null ? 0 : this.getReferencia()
						.hashCode());
		result = 37 * result
				+ (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37
				* result
				+ (getApellidoPaterno() == null ? 0 : this.getApellidoPaterno()
						.hashCode());
		result = 37
				* result
				+ (getApellidoMaterno() == null ? 0 : this.getApellidoMaterno()
						.hashCode());
		result = 37 * result
				+ (getComision() == null ? 0 : this.getComision().hashCode());
		result = 37 * result
				+ (getPromotor() == null ? 0 : this.getPromotor().hashCode());
		result = 37
				* result
				+ (getTelefonoCasa() == null ? 0 : this.getTelefonoCasa()
						.hashCode());
		result = 37 * result
				+ (getCelular() == null ? 0 : this.getCelular().hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result
				+ (getCalle() == null ? 0 : this.getCalle().hashCode());
		result = 37
				* result
				+ (getNumeroExterior() == null ? 0 : this.getNumeroExterior()
						.hashCode());
		result = 37
				* result
				+ (getNumeroInterior() == null ? 0 : this.getNumeroInterior()
						.hashCode());
		result = 37 * result
				+ (getColonia() == null ? 0 : this.getColonia().hashCode());
		result = 37 * result
				+ (getCiudad() == null ? 0 : this.getCiudad().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getReplica() == null ? 0 : this.getReplica().hashCode());
		result = 37 * result + (getCp() == null ? 0 : this.getCp().hashCode());
		result = 37 * result
				+ (getSector() == null ? 0 : this.getSector().hashCode());
		result = 37
				* result
				+ (getTalonarios() == null ? 0 : this.getTalonarios()
						.hashCode());
		result = 37 * result
				+ (getBoletos() == null ? 0 : this.getBoletos().hashCode());
		result = 37 * result
				+ (getFc3() == null ? 0 : this.getFc3().hashCode());
		result = 37 * result
				+ (getFc4() == null ? 0 : this.getFc4().hashCode());
		result = 37 * result
				+ (getFc4b() == null ? 0 : this.getFc4b().hashCode());
		result = 37
				* result
				+ (getFc4bVendido() == null ? 0 : this.getFc4bVendido()
						.hashCode());
		result = 37
				* result
				+ (getBoletosVendidos() == null ? 0 : this.getBoletosVendidos()
						.hashCode());
		result = 37 * result
				+ (getMonto() == null ? 0 : this.getMonto().hashCode());
		result = 37
				* result
				+ (getAbonoDevolucion() == null ? 0 : this.getAbonoDevolucion()
						.hashCode());
		result = 37 * result
				+ (getNominas() == null ? 0 : this.getNominas().hashCode());
		result = 37
				* result
				+ (getNominasFuv() == null ? 0 : this.getNominasFuv()
						.hashCode());
		result = 37 * result
				+ (getDpnNetos() == null ? 0 : this.getDpnNetos().hashCode());
		result = 37 * result
				+ (getPagosNeto() == null ? 0 : this.getPagosNeto().hashCode());
		result = 37 * result
				+ (getSaldos() == null ? 0 : this.getSaldos().hashCode());
		result = 37
				* result
				+ (getEstatusPago() == null ? 0 : this.getEstatusPago()
						.hashCode());
		result = 37
				* result
				+ (getEstatusCarteras() == null ? 0 : this.getEstatusCarteras()
						.hashCode());
		result = 37
				* result
				+ (getTipoColaborador() == null ? 0 : this.getTipoColaborador()
						.hashCode());
		result = 37
				* result
				+ (getBoletosElectronicos() == null ? 0 : this
						.getBoletosElectronicos().hashCode());
		result = 37 * result
				+ (getRegion() == null ? 0 : this.getRegion().hashCode());
		return result;
	}

}
