package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * MaestroColaboradorLocal generated by hbm2java
 */
public class MaestroColaboradorLocal implements java.io.Serializable {

	private MaestroColaboradorLocalId id;

	public MaestroColaboradorLocal() {
	}

	public MaestroColaboradorLocal(MaestroColaboradorLocalId id) {
		this.id = id;
	}

	public MaestroColaboradorLocalId getId() {
		return this.id;
	}

	public void setId(MaestroColaboradorLocalId id) {
		this.id = id;
	}

}
