package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Integer idRegion;
	private int idEstado;

	public Municipios() {
	}

	public Municipios(String nombre, int idEstado) {
		this.nombre = nombre;
		this.idEstado = idEstado;
	}

	public Municipios(String nombre, Integer idRegion, int idEstado) {
		this.nombre = nombre;
		this.idRegion = idRegion;
		this.idEstado = idEstado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

}
