package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * NominasFuv generated by hbm2java
 */
public class NominasFuv implements java.io.Serializable {

	private Integer id;
	private int idFc2;
	private Integer idColaborador;
	private Date inicioPago;
	private int numeroQuincenas;
	private int numeroBoletos;
	private int monto;
	private Date fechaRegistro;
	private int idUsuario;
	private String numeroDpn;

	public NominasFuv() {
	}

	public NominasFuv(int idFc2, Date inicioPago, int numeroQuincenas,
			int numeroBoletos, int monto, Date fechaRegistro, int idUsuario) {
		this.idFc2 = idFc2;
		this.inicioPago = inicioPago;
		this.numeroQuincenas = numeroQuincenas;
		this.numeroBoletos = numeroBoletos;
		this.monto = monto;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public NominasFuv(int idFc2, Integer idColaborador, Date inicioPago,
			int numeroQuincenas, int numeroBoletos, int monto,
			Date fechaRegistro, int idUsuario, String numeroDpn) {
		this.idFc2 = idFc2;
		this.idColaborador = idColaborador;
		this.inicioPago = inicioPago;
		this.numeroQuincenas = numeroQuincenas;
		this.numeroBoletos = numeroBoletos;
		this.monto = monto;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
		this.numeroDpn = numeroDpn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdFc2() {
		return this.idFc2;
	}

	public void setIdFc2(int idFc2) {
		this.idFc2 = idFc2;
	}

	public Integer getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(Integer idColaborador) {
		this.idColaborador = idColaborador;
	}

	public Date getInicioPago() {
		return this.inicioPago;
	}

	public void setInicioPago(Date inicioPago) {
		this.inicioPago = inicioPago;
	}

	public int getNumeroQuincenas() {
		return this.numeroQuincenas;
	}

	public void setNumeroQuincenas(int numeroQuincenas) {
		this.numeroQuincenas = numeroQuincenas;
	}

	public int getNumeroBoletos() {
		return this.numeroBoletos;
	}

	public void setNumeroBoletos(int numeroBoletos) {
		this.numeroBoletos = numeroBoletos;
	}

	public int getMonto() {
		return this.monto;
	}

	public void setMonto(int monto) {
		this.monto = monto;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getNumeroDpn() {
		return this.numeroDpn;
	}

	public void setNumeroDpn(String numeroDpn) {
		this.numeroDpn = numeroDpn;
	}

}
