package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos implements java.io.Serializable {

	private Integer id;
	private Integer idTipoPago;
	private Integer idResponsable;
	private Float monto;
	private Date fechaPago;
	private Character tipoResponsable;
	private String observaciones;
	private Integer idTabla;
	private int idSector;

	public Pagos() {
	}

	public Pagos(int idSector) {
		this.idSector = idSector;
	}

	public Pagos(Integer idTipoPago, Integer idResponsable, Float monto,
			Date fechaPago, Character tipoResponsable, String observaciones,
			Integer idTabla, int idSector) {
		this.idTipoPago = idTipoPago;
		this.idResponsable = idResponsable;
		this.monto = monto;
		this.fechaPago = fechaPago;
		this.tipoResponsable = tipoResponsable;
		this.observaciones = observaciones;
		this.idTabla = idTabla;
		this.idSector = idSector;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdTipoPago() {
		return this.idTipoPago;
	}

	public void setIdTipoPago(Integer idTipoPago) {
		this.idTipoPago = idTipoPago;
	}

	public Integer getIdResponsable() {
		return this.idResponsable;
	}

	public void setIdResponsable(Integer idResponsable) {
		this.idResponsable = idResponsable;
	}

	public Float getMonto() {
		return this.monto;
	}

	public void setMonto(Float monto) {
		this.monto = monto;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public Character getTipoResponsable() {
		return this.tipoResponsable;
	}

	public void setTipoResponsable(Character tipoResponsable) {
		this.tipoResponsable = tipoResponsable;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(Integer idTabla) {
		this.idTabla = idTabla;
	}

	public int getIdSector() {
		return this.idSector;
	}

	public void setIdSector(int idSector) {
		this.idSector = idSector;
	}

}
