package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * PremiosHistorial generated by hbm2java
 */
public class PremiosHistorial implements java.io.Serializable {

	private PremiosHistorialId id;

	public PremiosHistorial() {
	}

	public PremiosHistorial(PremiosHistorialId id) {
		this.id = id;
	}

	public PremiosHistorialId getId() {
		return this.id;
	}

	public void setId(PremiosHistorialId id) {
		this.id = id;
	}

}
