package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * PremiosHistorialId generated by hbm2java
 */
public class PremiosHistorialId implements java.io.Serializable {

	private int id;
	private int idSorteo;
	private int numeroPremio;
	private String nombre;
	private String descripcionLarga;
	private String descripcionCorta;
	private Double valorUnitario;
	private Integer idPremioAsignado;
	private Integer idGanador;
	private Integer idBoleto;
	private String lugar;
	private String fecha;
	private Integer idTipoIdentificacion;
	private String folio;
	private Integer auto;
	private String serie;
	private String factura;
	private String motor;
	private int anio;
	private String descMaterialesImpresos;

	public PremiosHistorialId() {
	}

	public PremiosHistorialId(int id, int idSorteo, int numeroPremio,
			String nombre, int anio) {
		this.id = id;
		this.idSorteo = idSorteo;
		this.numeroPremio = numeroPremio;
		this.nombre = nombre;
		this.anio = anio;
	}

	public PremiosHistorialId(int id, int idSorteo, int numeroPremio,
			String nombre, String descripcionLarga, String descripcionCorta,
			Double valorUnitario, Integer idPremioAsignado, Integer idGanador,
			Integer idBoleto, String lugar, String fecha,
			Integer idTipoIdentificacion, String folio, Integer auto,
			String serie, String factura, String motor, int anio,
			String descMaterialesImpresos) {
		this.id = id;
		this.idSorteo = idSorteo;
		this.numeroPremio = numeroPremio;
		this.nombre = nombre;
		this.descripcionLarga = descripcionLarga;
		this.descripcionCorta = descripcionCorta;
		this.valorUnitario = valorUnitario;
		this.idPremioAsignado = idPremioAsignado;
		this.idGanador = idGanador;
		this.idBoleto = idBoleto;
		this.lugar = lugar;
		this.fecha = fecha;
		this.idTipoIdentificacion = idTipoIdentificacion;
		this.folio = folio;
		this.auto = auto;
		this.serie = serie;
		this.factura = factura;
		this.motor = motor;
		this.anio = anio;
		this.descMaterialesImpresos = descMaterialesImpresos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdSorteo() {
		return this.idSorteo;
	}

	public void setIdSorteo(int idSorteo) {
		this.idSorteo = idSorteo;
	}

	public int getNumeroPremio() {
		return this.numeroPremio;
	}

	public void setNumeroPremio(int numeroPremio) {
		this.numeroPremio = numeroPremio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcionLarga() {
		return this.descripcionLarga;
	}

	public void setDescripcionLarga(String descripcionLarga) {
		this.descripcionLarga = descripcionLarga;
	}

	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	public Double getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(Double valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Integer getIdPremioAsignado() {
		return this.idPremioAsignado;
	}

	public void setIdPremioAsignado(Integer idPremioAsignado) {
		this.idPremioAsignado = idPremioAsignado;
	}

	public Integer getIdGanador() {
		return this.idGanador;
	}

	public void setIdGanador(Integer idGanador) {
		this.idGanador = idGanador;
	}

	public Integer getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(Integer idBoleto) {
		this.idBoleto = idBoleto;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Integer getIdTipoIdentificacion() {
		return this.idTipoIdentificacion;
	}

	public void setIdTipoIdentificacion(Integer idTipoIdentificacion) {
		this.idTipoIdentificacion = idTipoIdentificacion;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public Integer getAuto() {
		return this.auto;
	}

	public void setAuto(Integer auto) {
		this.auto = auto;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public String getDescMaterialesImpresos() {
		return this.descMaterialesImpresos;
	}

	public void setDescMaterialesImpresos(String descMaterialesImpresos) {
		this.descMaterialesImpresos = descMaterialesImpresos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PremiosHistorialId))
			return false;
		PremiosHistorialId castOther = (PremiosHistorialId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdSorteo() == castOther.getIdSorteo())
				&& (this.getNumeroPremio() == castOther.getNumeroPremio())
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getDescripcionLarga() == castOther
						.getDescripcionLarga()) || (this.getDescripcionLarga() != null
						&& castOther.getDescripcionLarga() != null && this
						.getDescripcionLarga().equals(
								castOther.getDescripcionLarga())))
				&& ((this.getDescripcionCorta() == castOther
						.getDescripcionCorta()) || (this.getDescripcionCorta() != null
						&& castOther.getDescripcionCorta() != null && this
						.getDescripcionCorta().equals(
								castOther.getDescripcionCorta())))
				&& ((this.getValorUnitario() == castOther.getValorUnitario()) || (this
						.getValorUnitario() != null
						&& castOther.getValorUnitario() != null && this
						.getValorUnitario()
						.equals(castOther.getValorUnitario())))
				&& ((this.getIdPremioAsignado() == castOther
						.getIdPremioAsignado()) || (this.getIdPremioAsignado() != null
						&& castOther.getIdPremioAsignado() != null && this
						.getIdPremioAsignado().equals(
								castOther.getIdPremioAsignado())))
				&& ((this.getIdGanador() == castOther.getIdGanador()) || (this
						.getIdGanador() != null
						&& castOther.getIdGanador() != null && this
						.getIdGanador().equals(castOther.getIdGanador())))
				&& ((this.getIdBoleto() == castOther.getIdBoleto()) || (this
						.getIdBoleto() != null
						&& castOther.getIdBoleto() != null && this
						.getIdBoleto().equals(castOther.getIdBoleto())))
				&& ((this.getLugar() == castOther.getLugar()) || (this
						.getLugar() != null && castOther.getLugar() != null && this
						.getLugar().equals(castOther.getLugar())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getIdTipoIdentificacion() == castOther
						.getIdTipoIdentificacion()) || (this
						.getIdTipoIdentificacion() != null
						&& castOther.getIdTipoIdentificacion() != null && this
						.getIdTipoIdentificacion().equals(
								castOther.getIdTipoIdentificacion())))
				&& ((this.getFolio() == castOther.getFolio()) || (this
						.getFolio() != null && castOther.getFolio() != null && this
						.getFolio().equals(castOther.getFolio())))
				&& ((this.getAuto() == castOther.getAuto()) || (this.getAuto() != null
						&& castOther.getAuto() != null && this.getAuto()
						.equals(castOther.getAuto())))
				&& ((this.getSerie() == castOther.getSerie()) || (this
						.getSerie() != null && castOther.getSerie() != null && this
						.getSerie().equals(castOther.getSerie())))
				&& ((this.getFactura() == castOther.getFactura()) || (this
						.getFactura() != null && castOther.getFactura() != null && this
						.getFactura().equals(castOther.getFactura())))
				&& ((this.getMotor() == castOther.getMotor()) || (this
						.getMotor() != null && castOther.getMotor() != null && this
						.getMotor().equals(castOther.getMotor())))
				&& (this.getAnio() == castOther.getAnio())
				&& ((this.getDescMaterialesImpresos() == castOther
						.getDescMaterialesImpresos()) || (this
						.getDescMaterialesImpresos() != null
						&& castOther.getDescMaterialesImpresos() != null && this
						.getDescMaterialesImpresos().equals(
								castOther.getDescMaterialesImpresos())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdSorteo();
		result = 37 * result + this.getNumeroPremio();
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37
				* result
				+ (getDescripcionLarga() == null ? 0 : this
						.getDescripcionLarga().hashCode());
		result = 37
				* result
				+ (getDescripcionCorta() == null ? 0 : this
						.getDescripcionCorta().hashCode());
		result = 37
				* result
				+ (getValorUnitario() == null ? 0 : this.getValorUnitario()
						.hashCode());
		result = 37
				* result
				+ (getIdPremioAsignado() == null ? 0 : this
						.getIdPremioAsignado().hashCode());
		result = 37 * result
				+ (getIdGanador() == null ? 0 : this.getIdGanador().hashCode());
		result = 37 * result
				+ (getIdBoleto() == null ? 0 : this.getIdBoleto().hashCode());
		result = 37 * result
				+ (getLugar() == null ? 0 : this.getLugar().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37
				* result
				+ (getIdTipoIdentificacion() == null ? 0 : this
						.getIdTipoIdentificacion().hashCode());
		result = 37 * result
				+ (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result
				+ (getAuto() == null ? 0 : this.getAuto().hashCode());
		result = 37 * result
				+ (getSerie() == null ? 0 : this.getSerie().hashCode());
		result = 37 * result
				+ (getFactura() == null ? 0 : this.getFactura().hashCode());
		result = 37 * result
				+ (getMotor() == null ? 0 : this.getMotor().hashCode());
		result = 37 * result + this.getAnio();
		result = 37
				* result
				+ (getDescMaterialesImpresos() == null ? 0 : this
						.getDescMaterialesImpresos().hashCode());
		return result;
	}

}
