package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PromoMarketingBitacora generated by hbm2java
 */
public class PromoMarketingBitacora implements java.io.Serializable {

	private Integer id;
	private int idPromocional;
	private String nombre;
	private int cantidad;
	private String fecha;
	private Date fechaActualiza;

	public PromoMarketingBitacora() {
	}

	public PromoMarketingBitacora(int idPromocional, String nombre,
			int cantidad, Date fechaActualiza) {
		this.idPromocional = idPromocional;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.fechaActualiza = fechaActualiza;
	}

	public PromoMarketingBitacora(int idPromocional, String nombre,
			int cantidad, String fecha, Date fechaActualiza) {
		this.idPromocional = idPromocional;
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.fechaActualiza = fechaActualiza;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdPromocional() {
		return this.idPromocional;
	}

	public void setIdPromocional(int idPromocional) {
		this.idPromocional = idPromocional;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Date getFechaActualiza() {
		return this.fechaActualiza;
	}

	public void setFechaActualiza(Date fechaActualiza) {
		this.fechaActualiza = fechaActualiza;
	}

}
