package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PromotoresFormatos generated by hbm2java
 */
public class PromotoresFormatos implements java.io.Serializable {

	private Integer id;
	private int idPromotor;
	private int idFormato;
	private char estatus;
	private Date fecha;
	private int idUsuario;

	public PromotoresFormatos() {
	}

	public PromotoresFormatos(int idPromotor, int idFormato, char estatus,
			Date fecha, int idUsuario) {
		this.idPromotor = idPromotor;
		this.idFormato = idFormato;
		this.estatus = estatus;
		this.fecha = fecha;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(int idPromotor) {
		this.idPromotor = idPromotor;
	}

	public int getIdFormato() {
		return this.idFormato;
	}

	public void setIdFormato(int idFormato) {
		this.idFormato = idFormato;
	}

	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
