package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Puestos generated by hbm2java
 */
public class Puestos implements java.io.Serializable {

	private Integer id;
	private String puesto;
	private int idArea;

	public Puestos() {
	}

	public Puestos(String puesto, int idArea) {
		this.puesto = puesto;
		this.idArea = idArea;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	public int getIdArea() {
		return this.idArea;
	}

	public void setIdArea(int idArea) {
		this.idArea = idArea;
	}

}
