package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * RangosCarterasBoletos generated by hbm2java
 */
public class RangosCarterasBoletos implements java.io.Serializable {

	private Integer id;
	private Integer numeroBoletos;
	private String folioInicio;
	private String folioFin;

	public RangosCarterasBoletos() {
	}

	public RangosCarterasBoletos(Integer numeroBoletos, String folioInicio,
			String folioFin) {
		this.numeroBoletos = numeroBoletos;
		this.folioInicio = folioInicio;
		this.folioFin = folioFin;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getNumeroBoletos() {
		return this.numeroBoletos;
	}

	public void setNumeroBoletos(Integer numeroBoletos) {
		this.numeroBoletos = numeroBoletos;
	}

	public String getFolioInicio() {
		return this.folioInicio;
	}

	public void setFolioInicio(String folioInicio) {
		this.folioInicio = folioInicio;
	}

	public String getFolioFin() {
		return this.folioFin;
	}

	public void setFolioFin(String folioFin) {
		this.folioFin = folioFin;
	}

}
