package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * RecibosHistorialId generated by hbm2java
 */
public class RecibosHistorialId implements java.io.Serializable {

	private int id;
	private int idPremio;
	private String lugar;
	private String fecha;
	private String serie;
	private String motor;
	private String circulacion;
	private String factura;
	private int idTipoIdentificacion;
	private String folio;
	private int anio;

	public RecibosHistorialId() {
	}

	public RecibosHistorialId(int id, int idPremio, String lugar, String fecha,
			int idTipoIdentificacion, String folio, int anio) {
		this.id = id;
		this.idPremio = idPremio;
		this.lugar = lugar;
		this.fecha = fecha;
		this.idTipoIdentificacion = idTipoIdentificacion;
		this.folio = folio;
		this.anio = anio;
	}

	public RecibosHistorialId(int id, int idPremio, String lugar, String fecha,
			String serie, String motor, String circulacion, String factura,
			int idTipoIdentificacion, String folio, int anio) {
		this.id = id;
		this.idPremio = idPremio;
		this.lugar = lugar;
		this.fecha = fecha;
		this.serie = serie;
		this.motor = motor;
		this.circulacion = circulacion;
		this.factura = factura;
		this.idTipoIdentificacion = idTipoIdentificacion;
		this.folio = folio;
		this.anio = anio;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdPremio() {
		return this.idPremio;
	}

	public void setIdPremio(int idPremio) {
		this.idPremio = idPremio;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public String getCirculacion() {
		return this.circulacion;
	}

	public void setCirculacion(String circulacion) {
		this.circulacion = circulacion;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public int getIdTipoIdentificacion() {
		return this.idTipoIdentificacion;
	}

	public void setIdTipoIdentificacion(int idTipoIdentificacion) {
		this.idTipoIdentificacion = idTipoIdentificacion;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public int getAnio() {
		return this.anio;
	}

	public void setAnio(int anio) {
		this.anio = anio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecibosHistorialId))
			return false;
		RecibosHistorialId castOther = (RecibosHistorialId) other;

		return (this.getId() == castOther.getId())
				&& (this.getIdPremio() == castOther.getIdPremio())
				&& ((this.getLugar() == castOther.getLugar()) || (this
						.getLugar() != null && castOther.getLugar() != null && this
						.getLugar().equals(castOther.getLugar())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())))
				&& ((this.getSerie() == castOther.getSerie()) || (this
						.getSerie() != null && castOther.getSerie() != null && this
						.getSerie().equals(castOther.getSerie())))
				&& ((this.getMotor() == castOther.getMotor()) || (this
						.getMotor() != null && castOther.getMotor() != null && this
						.getMotor().equals(castOther.getMotor())))
				&& ((this.getCirculacion() == castOther.getCirculacion()) || (this
						.getCirculacion() != null
						&& castOther.getCirculacion() != null && this
						.getCirculacion().equals(castOther.getCirculacion())))
				&& ((this.getFactura() == castOther.getFactura()) || (this
						.getFactura() != null && castOther.getFactura() != null && this
						.getFactura().equals(castOther.getFactura())))
				&& (this.getIdTipoIdentificacion() == castOther
						.getIdTipoIdentificacion())
				&& ((this.getFolio() == castOther.getFolio()) || (this
						.getFolio() != null && castOther.getFolio() != null && this
						.getFolio().equals(castOther.getFolio())))
				&& (this.getAnio() == castOther.getAnio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getIdPremio();
		result = 37 * result
				+ (getLugar() == null ? 0 : this.getLugar().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getSerie() == null ? 0 : this.getSerie().hashCode());
		result = 37 * result
				+ (getMotor() == null ? 0 : this.getMotor().hashCode());
		result = 37
				* result
				+ (getCirculacion() == null ? 0 : this.getCirculacion()
						.hashCode());
		result = 37 * result
				+ (getFactura() == null ? 0 : this.getFactura().hashCode());
		result = 37 * result + this.getIdTipoIdentificacion();
		result = 37 * result
				+ (getFolio() == null ? 0 : this.getFolio().hashCode());
		result = 37 * result + this.getAnio();
		return result;
	}

}
