package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * RecibosHistorial generated by hbm2java
 */
public class RecibosHistorial implements java.io.Serializable {

	private RecibosHistorialId id;

	public RecibosHistorial() {
	}

	public RecibosHistorial(RecibosHistorialId id) {
		this.id = id;
	}

	public RecibosHistorialId getId() {
		return this.id;
	}

	public void setId(RecibosHistorialId id) {
		this.id = id;
	}

}
