package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Referencias generated by hbm2java
 */
public class Referencias implements java.io.Serializable {

	private Integer id;
	private String referencia;
	private int estatus;
	private Integer idRegion;
	private int tipoColaborador;
	private int cita;

	public Referencias() {
	}

	public Referencias(String referencia, int estatus, int tipoColaborador,
			int cita) {
		this.referencia = referencia;
		this.estatus = estatus;
		this.tipoColaborador = tipoColaborador;
		this.cita = cita;
	}

	public Referencias(String referencia, int estatus, Integer idRegion,
			int tipoColaborador, int cita) {
		this.referencia = referencia;
		this.estatus = estatus;
		this.idRegion = idRegion;
		this.tipoColaborador = tipoColaborador;
		this.cita = cita;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

	public int getTipoColaborador() {
		return this.tipoColaborador;
	}

	public void setTipoColaborador(int tipoColaborador) {
		this.tipoColaborador = tipoColaborador;
	}

	public int getCita() {
		return this.cita;
	}

	public void setCita(int cita) {
		this.cita = cita;
	}

}
