package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * RegistroEstudiantes generated by hbm2java
 */
public class RegistroEstudiantes implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String lineacaptura;
	private String pwd;
	private String masDatos;
	private Date fechaRegistro;
	private String precio;
	private Integer estatus;

	public RegistroEstudiantes() {
	}

	public RegistroEstudiantes(String nombre, String lineacaptura, String pwd,
			String masDatos, Date fechaRegistro, String precio, Integer estatus) {
		this.nombre = nombre;
		this.lineacaptura = lineacaptura;
		this.pwd = pwd;
		this.masDatos = masDatos;
		this.fechaRegistro = fechaRegistro;
		this.precio = precio;
		this.estatus = estatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getLineacaptura() {
		return this.lineacaptura;
	}

	public void setLineacaptura(String lineacaptura) {
		this.lineacaptura = lineacaptura;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getMasDatos() {
		return this.masDatos;
	}

	public void setMasDatos(String masDatos) {
		this.masDatos = masDatos;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getPrecio() {
		return this.precio;
	}

	public void setPrecio(String precio) {
		this.precio = precio;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

}
