package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * SaldoColaboradorLocal generated by hbm2java
 */
public class SaldoColaboradorLocal implements java.io.Serializable {

	private SaldoColaboradorLocalId id;

	public SaldoColaboradorLocal() {
	}

	public SaldoColaboradorLocal(SaldoColaboradorLocalId id) {
		this.id = id;
	}

	public SaldoColaboradorLocalId getId() {
		return this.id;
	}

	public void setId(SaldoColaboradorLocalId id) {
		this.id = id;
	}

}
