package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * SorteoMagnoHistorial generated by hbm2java
 */
public class SorteoMagnoHistorial implements java.io.Serializable {

	private SorteoMagnoHistorialId id;

	public SorteoMagnoHistorial() {
	}

	public SorteoMagnoHistorial(SorteoMagnoHistorialId id) {
		this.id = id;
	}

	public SorteoMagnoHistorialId getId() {
		return this.id;
	}

	public void setId(SorteoMagnoHistorialId id) {
		this.id = id;
	}

}
