package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Sorteos generated by hbm2java
 */
public class Sorteos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Date fechaSorteo;
	private String permisoGobernacion;
	private String cuenta;
	private Integer folioInicial;
	private Integer folioFinal;
	private Integer folioMaximo;
	private Integer vigente;
	private Integer tipo;
	private int precioReal;
	private int precioComision;
	private Integer numeroColaboradores;
	private Date fechaEntrega;
	private Date fechaLimitePago;

	public Sorteos() {
	}

	public Sorteos(String nombre, Date fechaSorteo, String permisoGobernacion,
			int precioReal, int precioComision) {
		this.nombre = nombre;
		this.fechaSorteo = fechaSorteo;
		this.permisoGobernacion = permisoGobernacion;
		this.precioReal = precioReal;
		this.precioComision = precioComision;
	}

	public Sorteos(String nombre, Date fechaSorteo, String permisoGobernacion,
			String cuenta, Integer folioInicial, Integer folioFinal,
			Integer folioMaximo, Integer vigente, Integer tipo, int precioReal,
			int precioComision, Integer numeroColaboradores, Date fechaEntrega,
			Date fechaLimitePago) {
		this.nombre = nombre;
		this.fechaSorteo = fechaSorteo;
		this.permisoGobernacion = permisoGobernacion;
		this.cuenta = cuenta;
		this.folioInicial = folioInicial;
		this.folioFinal = folioFinal;
		this.folioMaximo = folioMaximo;
		this.vigente = vigente;
		this.tipo = tipo;
		this.precioReal = precioReal;
		this.precioComision = precioComision;
		this.numeroColaboradores = numeroColaboradores;
		this.fechaEntrega = fechaEntrega;
		this.fechaLimitePago = fechaLimitePago;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaSorteo() {
		return this.fechaSorteo;
	}

	public void setFechaSorteo(Date fechaSorteo) {
		this.fechaSorteo = fechaSorteo;
	}

	public String getPermisoGobernacion() {
		return this.permisoGobernacion;
	}

	public void setPermisoGobernacion(String permisoGobernacion) {
		this.permisoGobernacion = permisoGobernacion;
	}

	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public Integer getFolioInicial() {
		return this.folioInicial;
	}

	public void setFolioInicial(Integer folioInicial) {
		this.folioInicial = folioInicial;
	}

	public Integer getFolioFinal() {
		return this.folioFinal;
	}

	public void setFolioFinal(Integer folioFinal) {
		this.folioFinal = folioFinal;
	}

	public Integer getFolioMaximo() {
		return this.folioMaximo;
	}

	public void setFolioMaximo(Integer folioMaximo) {
		this.folioMaximo = folioMaximo;
	}

	public Integer getVigente() {
		return this.vigente;
	}

	public void setVigente(Integer vigente) {
		this.vigente = vigente;
	}

	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public int getPrecioReal() {
		return this.precioReal;
	}

	public void setPrecioReal(int precioReal) {
		this.precioReal = precioReal;
	}

	public int getPrecioComision() {
		return this.precioComision;
	}

	public void setPrecioComision(int precioComision) {
		this.precioComision = precioComision;
	}

	public Integer getNumeroColaboradores() {
		return this.numeroColaboradores;
	}

	public void setNumeroColaboradores(Integer numeroColaboradores) {
		this.numeroColaboradores = numeroColaboradores;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public Date getFechaLimitePago() {
		return this.fechaLimitePago;
	}

	public void setFechaLimitePago(Date fechaLimitePago) {
		this.fechaLimitePago = fechaLimitePago;
	}

}
