package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * SorteoEstudiantes generated by hbm2java
 */
public class SorteoEstudiantes implements java.io.Serializable {

	private Integer id;
	private int idBoleto;
	private int estatus;
	private int idPremio;
	private String boleto;
	private String estudiante;
	private Integer premio;
	private Integer idSorteo;
	private String aclaracion;
	private String donde;
	private String debe;

	public SorteoEstudiantes() {
	}

	public SorteoEstudiantes(int idBoleto, int estatus, int idPremio) {
		this.idBoleto = idBoleto;
		this.estatus = estatus;
		this.idPremio = idPremio;
	}

	public SorteoEstudiantes(int idBoleto, int estatus, int idPremio,
			String boleto, String estudiante, Integer premio, Integer idSorteo,
			String aclaracion, String donde, String debe) {
		this.idBoleto = idBoleto;
		this.estatus = estatus;
		this.idPremio = idPremio;
		this.boleto = boleto;
		this.estudiante = estudiante;
		this.premio = premio;
		this.idSorteo = idSorteo;
		this.aclaracion = aclaracion;
		this.donde = donde;
		this.debe = debe;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public int getIdPremio() {
		return this.idPremio;
	}

	public void setIdPremio(int idPremio) {
		this.idPremio = idPremio;
	}

	public String getBoleto() {
		return this.boleto;
	}

	public void setBoleto(String boleto) {
		this.boleto = boleto;
	}

	public String getEstudiante() {
		return this.estudiante;
	}

	public void setEstudiante(String estudiante) {
		this.estudiante = estudiante;
	}

	public Integer getPremio() {
		return this.premio;
	}

	public void setPremio(Integer premio) {
		this.premio = premio;
	}

	public Integer getIdSorteo() {
		return this.idSorteo;
	}

	public void setIdSorteo(Integer idSorteo) {
		this.idSorteo = idSorteo;
	}

	public String getAclaracion() {
		return this.aclaracion;
	}

	public void setAclaracion(String aclaracion) {
		this.aclaracion = aclaracion;
	}

	public String getDonde() {
		return this.donde;
	}

	public void setDonde(String donde) {
		this.donde = donde;
	}

	public String getDebe() {
		return this.debe;
	}

	public void setDebe(String debe) {
		this.debe = debe;
	}

}
