package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TiposPersonalId generated by hbm2java
 */
public class TiposPersonalId implements java.io.Serializable {

	private int id;
	private String tipo;

	public TiposPersonalId() {
	}

	public TiposPersonalId(int id, String tipo) {
		this.id = id;
		this.tipo = tipo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TiposPersonalId))
			return false;
		TiposPersonalId castOther = (TiposPersonalId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
