package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TiposPersonal generated by hbm2java
 */
public class TiposPersonal implements java.io.Serializable {

	private TiposPersonalId id;

	public TiposPersonal() {
	}

	public TiposPersonal(TiposPersonalId id) {
		this.id = id;
	}

	public TiposPersonalId getId() {
		return this.id;
	}

	public void setId(TiposPersonalId id) {
		this.id = id;
	}

}
