package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TiposCompradores generated by hbm2java
 */
public class TiposCompradores implements java.io.Serializable {

	private Integer id;
	private String tipo;
	private Integer estatus;

	public TiposCompradores() {
	}

	public TiposCompradores(String tipo) {
		this.tipo = tipo;
	}

	public TiposCompradores(String tipo, Integer estatus) {
		this.tipo = tipo;
		this.estatus = estatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

}
