package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TiposContratacion generated by hbm2java
 */
public class TiposContratacion implements java.io.Serializable {

	private TiposContratacionId id;

	public TiposContratacion() {
	}

	public TiposContratacion(TiposContratacionId id) {
		this.id = id;
	}

	public TiposContratacionId getId() {
		return this.id;
	}

	public void setId(TiposContratacionId id) {
		this.id = id;
	}

}
