package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Traspasos generated by hbm2java
 */
public class Traspasos implements java.io.Serializable {

	private Integer id;
	private Integer idReferenciaOrigen;
	private Integer idColaboradorAsigno;
	private Integer monto;
	private Date fechaPago;
	private Date fechaAlta;
	private int idUsuario;
	private Integer idPagoOrigen;
	private Integer idPagoDestino;

	public Traspasos() {
	}

	public Traspasos(Date fechaPago, int idUsuario) {
		this.fechaPago = fechaPago;
		this.idUsuario = idUsuario;
	}

	public Traspasos(Integer idReferenciaOrigen, Integer idColaboradorAsigno,
			Integer monto, Date fechaPago, Date fechaAlta, int idUsuario,
			Integer idPagoOrigen, Integer idPagoDestino) {
		this.idReferenciaOrigen = idReferenciaOrigen;
		this.idColaboradorAsigno = idColaboradorAsigno;
		this.monto = monto;
		this.fechaPago = fechaPago;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.idPagoOrigen = idPagoOrigen;
		this.idPagoDestino = idPagoDestino;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdReferenciaOrigen() {
		return this.idReferenciaOrigen;
	}

	public void setIdReferenciaOrigen(Integer idReferenciaOrigen) {
		this.idReferenciaOrigen = idReferenciaOrigen;
	}

	public Integer getIdColaboradorAsigno() {
		return this.idColaboradorAsigno;
	}

	public void setIdColaboradorAsigno(Integer idColaboradorAsigno) {
		this.idColaboradorAsigno = idColaboradorAsigno;
	}

	public Integer getMonto() {
		return this.monto;
	}

	public void setMonto(Integer monto) {
		this.monto = monto;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getIdPagoOrigen() {
		return this.idPagoOrigen;
	}

	public void setIdPagoOrigen(Integer idPagoOrigen) {
		this.idPagoOrigen = idPagoOrigen;
	}

	public Integer getIdPagoDestino() {
		return this.idPagoDestino;
	}

	public void setIdPagoDestino(Integer idPagoDestino) {
		this.idPagoDestino = idPagoDestino;
	}

}
