package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Trfc2fc1b generated by hbm2java
 */
public class Trfc2fc1b implements java.io.Serializable {

	private Trfc2fc1bId id;

	public Trfc2fc1b() {
	}

	public Trfc2fc1b(Trfc2fc1bId id) {
		this.id = id;
	}

	public Trfc2fc1bId getId() {
		return this.id;
	}

	public void setId(Trfc2fc1bId id) {
		this.id = id;
	}

}
