package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewColaboradoresTodo generated by hbm2java
 */
public class ViewColaboradoresTodo implements java.io.Serializable {

	private ViewColaboradoresTodoId id;

	public ViewColaboradoresTodo() {
	}

	public ViewColaboradoresTodo(ViewColaboradoresTodoId id) {
		this.id = id;
	}

	public ViewColaboradoresTodoId getId() {
		return this.id;
	}

	public void setId(ViewColaboradoresTodoId id) {
		this.id = id;
	}

}
