package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewColaboradoresTodoId generated by hbm2java
 */
public class ViewColaboradoresTodoId implements java.io.Serializable {

	private int id;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private Date fechaNacimiento;
	private String calle;
	private String numeroInterior;
	private String numeroExterior;
	private int idEstado;
	private int idMunicipio;
	private int idLocalidad;
	private String idCodigoPostal;
	private int idPromotor;
	private int tipo;
	private Integer idTipoColaborador;
	private String telefonoCasa;
	private String telefonoOficina;
	private String celular;
	private String correo;
	private Integer idReferencia;
	private String rfc;
	private Date fechaAlta;
	private int idUsuario;
	private Integer documentacionMinima;
	private int estatus;
	private String numeroPersonal;
	private String preregistro;
	private String estado;
	private String municipio;
	private String localidad;
	private String cp;
	private String nombre;
	private String tipoColaborador;
	private String promotor;
	private String referencia;
	private Integer idEstudiante;
	private Integer replica;
	private String extensionOficina;

	public ViewColaboradoresTodoId() {
	}

	public ViewColaboradoresTodoId(int id, String nombres,
			String apellidoPaterno, String calle, String numeroExterior,
			int idEstado, int idMunicipio, int idLocalidad,
			String idCodigoPostal, int idPromotor, int tipo, String rfc,
			Date fechaAlta, int idUsuario, int estatus, String numeroPersonal,
			String tipoColaborador) {
		this.id = id;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idLocalidad = idLocalidad;
		this.idCodigoPostal = idCodigoPostal;
		this.idPromotor = idPromotor;
		this.tipo = tipo;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.estatus = estatus;
		this.numeroPersonal = numeroPersonal;
		this.tipoColaborador = tipoColaborador;
	}

	public ViewColaboradoresTodoId(int id, String nombres,
			String apellidoPaterno, String apellidoMaterno,
			Date fechaNacimiento, String calle, String numeroInterior,
			String numeroExterior, int idEstado, int idMunicipio,
			int idLocalidad, String idCodigoPostal, int idPromotor, int tipo,
			Integer idTipoColaborador, String telefonoCasa,
			String telefonoOficina, String celular, String correo,
			Integer idReferencia, String rfc, Date fechaAlta, int idUsuario,
			Integer documentacionMinima, int estatus, String numeroPersonal,
			String preregistro, String estado, String municipio,
			String localidad, String cp, String nombre, String tipoColaborador,
			String promotor, String referencia, Integer idEstudiante,
			Integer replica, String extensionOficina) {
		this.id = id;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.fechaNacimiento = fechaNacimiento;
		this.calle = calle;
		this.numeroInterior = numeroInterior;
		this.numeroExterior = numeroExterior;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idLocalidad = idLocalidad;
		this.idCodigoPostal = idCodigoPostal;
		this.idPromotor = idPromotor;
		this.tipo = tipo;
		this.idTipoColaborador = idTipoColaborador;
		this.telefonoCasa = telefonoCasa;
		this.telefonoOficina = telefonoOficina;
		this.celular = celular;
		this.correo = correo;
		this.idReferencia = idReferencia;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.documentacionMinima = documentacionMinima;
		this.estatus = estatus;
		this.numeroPersonal = numeroPersonal;
		this.preregistro = preregistro;
		this.estado = estado;
		this.municipio = municipio;
		this.localidad = localidad;
		this.cp = cp;
		this.nombre = nombre;
		this.tipoColaborador = tipoColaborador;
		this.promotor = promotor;
		this.referencia = referencia;
		this.idEstudiante = idEstudiante;
		this.replica = replica;
		this.extensionOficina = extensionOficina;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public String getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(String idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	public int getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(int idPromotor) {
		this.idPromotor = idPromotor;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public Integer getIdTipoColaborador() {
		return this.idTipoColaborador;
	}

	public void setIdTipoColaborador(Integer idTipoColaborador) {
		this.idTipoColaborador = idTipoColaborador;
	}

	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		this.telefonoOficina = telefonoOficina;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Integer getIdReferencia() {
		return this.idReferencia;
	}

	public void setIdReferencia(Integer idReferencia) {
		this.idReferencia = idReferencia;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getDocumentacionMinima() {
		return this.documentacionMinima;
	}

	public void setDocumentacionMinima(Integer documentacionMinima) {
		this.documentacionMinima = documentacionMinima;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(String numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	public String getPreregistro() {
		return this.preregistro;
	}

	public void setPreregistro(String preregistro) {
		this.preregistro = preregistro;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoColaborador() {
		return this.tipoColaborador;
	}

	public void setTipoColaborador(String tipoColaborador) {
		this.tipoColaborador = tipoColaborador;
	}

	public String getPromotor() {
		return this.promotor;
	}

	public void setPromotor(String promotor) {
		this.promotor = promotor;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public Integer getIdEstudiante() {
		return this.idEstudiante;
	}

	public void setIdEstudiante(Integer idEstudiante) {
		this.idEstudiante = idEstudiante;
	}

	public Integer getReplica() {
		return this.replica;
	}

	public void setReplica(Integer replica) {
		this.replica = replica;
	}

	public String getExtensionOficina() {
		return this.extensionOficina;
	}

	public void setExtensionOficina(String extensionOficina) {
		this.extensionOficina = extensionOficina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewColaboradoresTodoId))
			return false;
		ViewColaboradoresTodoId castOther = (ViewColaboradoresTodoId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getNombres() == castOther.getNombres()) || (this
						.getNombres() != null && castOther.getNombres() != null && this
						.getNombres().equals(castOther.getNombres())))
				&& ((this.getApellidoPaterno() == castOther
						.getApellidoPaterno()) || (this.getApellidoPaterno() != null
						&& castOther.getApellidoPaterno() != null && this
						.getApellidoPaterno().equals(
								castOther.getApellidoPaterno())))
				&& ((this.getApellidoMaterno() == castOther
						.getApellidoMaterno()) || (this.getApellidoMaterno() != null
						&& castOther.getApellidoMaterno() != null && this
						.getApellidoMaterno().equals(
								castOther.getApellidoMaterno())))
				&& ((this.getFechaNacimiento() == castOther
						.getFechaNacimiento()) || (this.getFechaNacimiento() != null
						&& castOther.getFechaNacimiento() != null && this
						.getFechaNacimiento().equals(
								castOther.getFechaNacimiento())))
				&& ((this.getCalle() == castOther.getCalle()) || (this
						.getCalle() != null && castOther.getCalle() != null && this
						.getCalle().equals(castOther.getCalle())))
				&& ((this.getNumeroInterior() == castOther.getNumeroInterior()) || (this
						.getNumeroInterior() != null
						&& castOther.getNumeroInterior() != null && this
						.getNumeroInterior().equals(
								castOther.getNumeroInterior())))
				&& ((this.getNumeroExterior() == castOther.getNumeroExterior()) || (this
						.getNumeroExterior() != null
						&& castOther.getNumeroExterior() != null && this
						.getNumeroExterior().equals(
								castOther.getNumeroExterior())))
				&& (this.getIdEstado() == castOther.getIdEstado())
				&& (this.getIdMunicipio() == castOther.getIdMunicipio())
				&& (this.getIdLocalidad() == castOther.getIdLocalidad())
				&& ((this.getIdCodigoPostal() == castOther.getIdCodigoPostal()) || (this
						.getIdCodigoPostal() != null
						&& castOther.getIdCodigoPostal() != null && this
						.getIdCodigoPostal().equals(
								castOther.getIdCodigoPostal())))
				&& (this.getIdPromotor() == castOther.getIdPromotor())
				&& (this.getTipo() == castOther.getTipo())
				&& ((this.getIdTipoColaborador() == castOther
						.getIdTipoColaborador()) || (this
						.getIdTipoColaborador() != null
						&& castOther.getIdTipoColaborador() != null && this
						.getIdTipoColaborador().equals(
								castOther.getIdTipoColaborador())))
				&& ((this.getTelefonoCasa() == castOther.getTelefonoCasa()) || (this
						.getTelefonoCasa() != null
						&& castOther.getTelefonoCasa() != null && this
						.getTelefonoCasa().equals(castOther.getTelefonoCasa())))
				&& ((this.getTelefonoOficina() == castOther
						.getTelefonoOficina()) || (this.getTelefonoOficina() != null
						&& castOther.getTelefonoOficina() != null && this
						.getTelefonoOficina().equals(
								castOther.getTelefonoOficina())))
				&& ((this.getCelular() == castOther.getCelular()) || (this
						.getCelular() != null && castOther.getCelular() != null && this
						.getCelular().equals(castOther.getCelular())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getIdReferencia() == castOther.getIdReferencia()) || (this
						.getIdReferencia() != null
						&& castOther.getIdReferencia() != null && this
						.getIdReferencia().equals(castOther.getIdReferencia())))
				&& ((this.getRfc() == castOther.getRfc()) || (this.getRfc() != null
						&& castOther.getRfc() != null && this.getRfc().equals(
						castOther.getRfc())))
				&& ((this.getFechaAlta() == castOther.getFechaAlta()) || (this
						.getFechaAlta() != null
						&& castOther.getFechaAlta() != null && this
						.getFechaAlta().equals(castOther.getFechaAlta())))
				&& (this.getIdUsuario() == castOther.getIdUsuario())
				&& ((this.getDocumentacionMinima() == castOther
						.getDocumentacionMinima()) || (this
						.getDocumentacionMinima() != null
						&& castOther.getDocumentacionMinima() != null && this
						.getDocumentacionMinima().equals(
								castOther.getDocumentacionMinima())))
				&& (this.getEstatus() == castOther.getEstatus())
				&& ((this.getNumeroPersonal() == castOther.getNumeroPersonal()) || (this
						.getNumeroPersonal() != null
						&& castOther.getNumeroPersonal() != null && this
						.getNumeroPersonal().equals(
								castOther.getNumeroPersonal())))
				&& ((this.getPreregistro() == castOther.getPreregistro()) || (this
						.getPreregistro() != null
						&& castOther.getPreregistro() != null && this
						.getPreregistro().equals(castOther.getPreregistro())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getMunicipio() == castOther.getMunicipio()) || (this
						.getMunicipio() != null
						&& castOther.getMunicipio() != null && this
						.getMunicipio().equals(castOther.getMunicipio())))
				&& ((this.getLocalidad() == castOther.getLocalidad()) || (this
						.getLocalidad() != null
						&& castOther.getLocalidad() != null && this
						.getLocalidad().equals(castOther.getLocalidad())))
				&& ((this.getCp() == castOther.getCp()) || (this.getCp() != null
						&& castOther.getCp() != null && this.getCp().equals(
						castOther.getCp())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getTipoColaborador() == castOther
						.getTipoColaborador()) || (this.getTipoColaborador() != null
						&& castOther.getTipoColaborador() != null && this
						.getTipoColaborador().equals(
								castOther.getTipoColaborador())))
				&& ((this.getPromotor() == castOther.getPromotor()) || (this
						.getPromotor() != null
						&& castOther.getPromotor() != null && this
						.getPromotor().equals(castOther.getPromotor())))
				&& ((this.getReferencia() == castOther.getReferencia()) || (this
						.getReferencia() != null
						&& castOther.getReferencia() != null && this
						.getReferencia().equals(castOther.getReferencia())))
				&& ((this.getIdEstudiante() == castOther.getIdEstudiante()) || (this
						.getIdEstudiante() != null
						&& castOther.getIdEstudiante() != null && this
						.getIdEstudiante().equals(castOther.getIdEstudiante())))
				&& ((this.getReplica() == castOther.getReplica()) || (this
						.getReplica() != null && castOther.getReplica() != null && this
						.getReplica().equals(castOther.getReplica())))
				&& ((this.getExtensionOficina() == castOther
						.getExtensionOficina()) || (this.getExtensionOficina() != null
						&& castOther.getExtensionOficina() != null && this
						.getExtensionOficina().equals(
								castOther.getExtensionOficina())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37
				* result
				+ (getApellidoPaterno() == null ? 0 : this.getApellidoPaterno()
						.hashCode());
		result = 37
				* result
				+ (getApellidoMaterno() == null ? 0 : this.getApellidoMaterno()
						.hashCode());
		result = 37
				* result
				+ (getFechaNacimiento() == null ? 0 : this.getFechaNacimiento()
						.hashCode());
		result = 37 * result
				+ (getCalle() == null ? 0 : this.getCalle().hashCode());
		result = 37
				* result
				+ (getNumeroInterior() == null ? 0 : this.getNumeroInterior()
						.hashCode());
		result = 37
				* result
				+ (getNumeroExterior() == null ? 0 : this.getNumeroExterior()
						.hashCode());
		result = 37 * result + this.getIdEstado();
		result = 37 * result + this.getIdMunicipio();
		result = 37 * result + this.getIdLocalidad();
		result = 37
				* result
				+ (getIdCodigoPostal() == null ? 0 : this.getIdCodigoPostal()
						.hashCode());
		result = 37 * result + this.getIdPromotor();
		result = 37 * result + this.getTipo();
		result = 37
				* result
				+ (getIdTipoColaborador() == null ? 0 : this
						.getIdTipoColaborador().hashCode());
		result = 37
				* result
				+ (getTelefonoCasa() == null ? 0 : this.getTelefonoCasa()
						.hashCode());
		result = 37
				* result
				+ (getTelefonoOficina() == null ? 0 : this.getTelefonoOficina()
						.hashCode());
		result = 37 * result
				+ (getCelular() == null ? 0 : this.getCelular().hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37
				* result
				+ (getIdReferencia() == null ? 0 : this.getIdReferencia()
						.hashCode());
		result = 37 * result
				+ (getRfc() == null ? 0 : this.getRfc().hashCode());
		result = 37 * result
				+ (getFechaAlta() == null ? 0 : this.getFechaAlta().hashCode());
		result = 37 * result + this.getIdUsuario();
		result = 37
				* result
				+ (getDocumentacionMinima() == null ? 0 : this
						.getDocumentacionMinima().hashCode());
		result = 37 * result + this.getEstatus();
		result = 37
				* result
				+ (getNumeroPersonal() == null ? 0 : this.getNumeroPersonal()
						.hashCode());
		result = 37
				* result
				+ (getPreregistro() == null ? 0 : this.getPreregistro()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getMunicipio() == null ? 0 : this.getMunicipio().hashCode());
		result = 37 * result
				+ (getLocalidad() == null ? 0 : this.getLocalidad().hashCode());
		result = 37 * result + (getCp() == null ? 0 : this.getCp().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37
				* result
				+ (getTipoColaborador() == null ? 0 : this.getTipoColaborador()
						.hashCode());
		result = 37 * result
				+ (getPromotor() == null ? 0 : this.getPromotor().hashCode());
		result = 37
				* result
				+ (getReferencia() == null ? 0 : this.getReferencia()
						.hashCode());
		result = 37
				* result
				+ (getIdEstudiante() == null ? 0 : this.getIdEstudiante()
						.hashCode());
		result = 37 * result
				+ (getReplica() == null ? 0 : this.getReplica().hashCode());
		result = 37
				* result
				+ (getExtensionOficina() == null ? 0 : this
						.getExtensionOficina().hashCode());
		return result;
	}

}
