package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewPermisosCatalogoMenu generated by hbm2java
 */
public class ViewPermisosCatalogoMenu implements java.io.Serializable {

	private ViewPermisosCatalogoMenuId id;

	public ViewPermisosCatalogoMenu() {
	}

	public ViewPermisosCatalogoMenu(ViewPermisosCatalogoMenuId id) {
		this.id = id;
	}

	public ViewPermisosCatalogoMenuId getId() {
		return this.id;
	}

	public void setId(ViewPermisosCatalogoMenuId id) {
		this.id = id;
	}

}
