package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewCompradoresNominaId generated by hbm2java
 */
public class ViewCompradoresNominaId implements java.io.Serializable {

	private int id;
	private String nombreCompleto;
	private String rfc;
	private Integer numeroPersonal;
	private Integer idTipoContratacion;
	private Integer idTipoPersonal;
	private int tipoComprador;
	private Integer idSector;
	private int idRegion;
	private Date fechaRegistro;
	private int idUsuario;

	public ViewCompradoresNominaId() {
	}

	public ViewCompradoresNominaId(int id, int tipoComprador, int idRegion,
			Date fechaRegistro, int idUsuario) {
		this.id = id;
		this.tipoComprador = tipoComprador;
		this.idRegion = idRegion;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public ViewCompradoresNominaId(int id, String nombreCompleto, String rfc,
			Integer numeroPersonal, Integer idTipoContratacion,
			Integer idTipoPersonal, int tipoComprador, Integer idSector,
			int idRegion, Date fechaRegistro, int idUsuario) {
		this.id = id;
		this.nombreCompleto = nombreCompleto;
		this.rfc = rfc;
		this.numeroPersonal = numeroPersonal;
		this.idTipoContratacion = idTipoContratacion;
		this.idTipoPersonal = idTipoPersonal;
		this.tipoComprador = tipoComprador;
		this.idSector = idSector;
		this.idRegion = idRegion;
		this.fechaRegistro = fechaRegistro;
		this.idUsuario = idUsuario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Integer getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(Integer numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	public Integer getIdTipoContratacion() {
		return this.idTipoContratacion;
	}

	public void setIdTipoContratacion(Integer idTipoContratacion) {
		this.idTipoContratacion = idTipoContratacion;
	}

	public Integer getIdTipoPersonal() {
		return this.idTipoPersonal;
	}

	public void setIdTipoPersonal(Integer idTipoPersonal) {
		this.idTipoPersonal = idTipoPersonal;
	}

	public int getTipoComprador() {
		return this.tipoComprador;
	}

	public void setTipoComprador(int tipoComprador) {
		this.tipoComprador = tipoComprador;
	}

	public Integer getIdSector() {
		return this.idSector;
	}

	public void setIdSector(Integer idSector) {
		this.idSector = idSector;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewCompradoresNominaId))
			return false;
		ViewCompradoresNominaId castOther = (ViewCompradoresNominaId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getNombreCompleto() == castOther.getNombreCompleto()) || (this
						.getNombreCompleto() != null
						&& castOther.getNombreCompleto() != null && this
						.getNombreCompleto().equals(
								castOther.getNombreCompleto())))
				&& ((this.getRfc() == castOther.getRfc()) || (this.getRfc() != null
						&& castOther.getRfc() != null && this.getRfc().equals(
						castOther.getRfc())))
				&& ((this.getNumeroPersonal() == castOther.getNumeroPersonal()) || (this
						.getNumeroPersonal() != null
						&& castOther.getNumeroPersonal() != null && this
						.getNumeroPersonal().equals(
								castOther.getNumeroPersonal())))
				&& ((this.getIdTipoContratacion() == castOther
						.getIdTipoContratacion()) || (this
						.getIdTipoContratacion() != null
						&& castOther.getIdTipoContratacion() != null && this
						.getIdTipoContratacion().equals(
								castOther.getIdTipoContratacion())))
				&& ((this.getIdTipoPersonal() == castOther.getIdTipoPersonal()) || (this
						.getIdTipoPersonal() != null
						&& castOther.getIdTipoPersonal() != null && this
						.getIdTipoPersonal().equals(
								castOther.getIdTipoPersonal())))
				&& (this.getTipoComprador() == castOther.getTipoComprador())
				&& ((this.getIdSector() == castOther.getIdSector()) || (this
						.getIdSector() != null
						&& castOther.getIdSector() != null && this
						.getIdSector().equals(castOther.getIdSector())))
				&& (this.getIdRegion() == castOther.getIdRegion())
				&& ((this.getFechaRegistro() == castOther.getFechaRegistro()) || (this
						.getFechaRegistro() != null
						&& castOther.getFechaRegistro() != null && this
						.getFechaRegistro()
						.equals(castOther.getFechaRegistro())))
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getNombreCompleto() == null ? 0 : this.getNombreCompleto()
						.hashCode());
		result = 37 * result
				+ (getRfc() == null ? 0 : this.getRfc().hashCode());
		result = 37
				* result
				+ (getNumeroPersonal() == null ? 0 : this.getNumeroPersonal()
						.hashCode());
		result = 37
				* result
				+ (getIdTipoContratacion() == null ? 0 : this
						.getIdTipoContratacion().hashCode());
		result = 37
				* result
				+ (getIdTipoPersonal() == null ? 0 : this.getIdTipoPersonal()
						.hashCode());
		result = 37 * result + this.getTipoComprador();
		result = 37 * result
				+ (getIdSector() == null ? 0 : this.getIdSector().hashCode());
		result = 37 * result + this.getIdRegion();
		result = 37
				* result
				+ (getFechaRegistro() == null ? 0 : this.getFechaRegistro()
						.hashCode());
		result = 37 * result + this.getIdUsuario();
		return result;
	}

}
