package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewColaboradoresId generated by hbm2java
 */
public class ViewColaboradoresId implements java.io.Serializable {

	private int id;
	private String rfc;
	private String nombreCompleto;

	public ViewColaboradoresId() {
	}

	public ViewColaboradoresId(int id, String rfc) {
		this.id = id;
		this.rfc = rfc;
	}

	public ViewColaboradoresId(int id, String rfc, String nombreCompleto) {
		this.id = id;
		this.rfc = rfc;
		this.nombreCompleto = nombreCompleto;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewColaboradoresId))
			return false;
		ViewColaboradoresId castOther = (ViewColaboradoresId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getRfc() == castOther.getRfc()) || (this.getRfc() != null
						&& castOther.getRfc() != null && this.getRfc().equals(
						castOther.getRfc())))
				&& ((this.getNombreCompleto() == castOther.getNombreCompleto()) || (this
						.getNombreCompleto() != null
						&& castOther.getNombreCompleto() != null && this
						.getNombreCompleto().equals(
								castOther.getNombreCompleto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getRfc() == null ? 0 : this.getRfc().hashCode());
		result = 37
				* result
				+ (getNombreCompleto() == null ? 0 : this.getNombreCompleto()
						.hashCode());
		return result;
	}

}
