package Pojos;

// Generated Jul 7, 2016 12:51:48 PM by Hibernate Tools 4.0.0

/**
 * VistaSectores generated by hbm2java
 */
public class VistaSectoresMeta implements java.io.Serializable {

	private int id;
	private int meta;
	

	public VistaSectoresMeta() {
	}

	public VistaSectoresMeta(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMeta() {
		return meta;
	}

	public void setMeta(int meta) {
		this.meta = meta;
	}

}
