package Pojos;

// Generated Jul 7, 2016 12:51:48 PM by Hibernate Tools 4.0.0

/**
 * VistaSectoresId generated by hbm2java
 */
public class VistaSectores implements java.io.Serializable {

	private int id;
	private String sector;
	private String comision;
	private int meta;
	private int idSectorPadre;
	private int idRegion;
	private int tipo;
	private int nivel;
	private String sectorRegion;
	private String region;
	private String sectorPadre;
	private int ultimo;

	public VistaSectores() {
	}

	public VistaSectores(int id, String sector, int idSectorPadre,
			int idRegion, int tipo, int nivel, String region, int ultimo) {
		this.id = id;
		this.sector = sector;
		this.idSectorPadre = idSectorPadre;
		this.idRegion = idRegion;
		this.tipo = tipo;
		this.nivel = nivel;
		this.region = region;
		this.setUltimo(ultimo);
	}
	
	public VistaSectores(int id, String sectorRegion, String comision, int meta, int nivel, int ultimo) {
		this.id = id;
		this.sectorRegion = sectorRegion;
		this.comision = comision;
		this.meta = meta;
		this.nivel = nivel;	
		this.setUltimo(ultimo);
	}

	public VistaSectores(int id, String sector, String comision, int meta,
			int idSectorPadre, int idRegion, int tipo, int nivel,
			String sectorRegion, String region, String sectorPadre) {
		this.id = id;
		this.sector = sector;
		this.comision = comision;
		this.meta = meta;
		this.idSectorPadre = idSectorPadre;
		this.idRegion = idRegion;
		this.tipo = tipo;
		this.nivel = nivel;
		this.sectorRegion = sectorRegion;
		this.region = region;
		this.sectorPadre = sectorPadre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public String getComision() {
		return this.comision;
	}

	public void setComision(String comision) {
		this.comision = comision;
	}

	public int getMeta() {
		return this.meta;
	}

	public void setMeta(int meta) {
		this.meta = meta;
	}

	public int getIdSectorPadre() {
		return this.idSectorPadre;
	}

	public void setIdSectorPadre(int idSectorPadre) {
		this.idSectorPadre = idSectorPadre;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public int getNivel() {
		return this.nivel;
	}

	public void setNivel(int nivel) {
		this.nivel = nivel;
	}

	public String getSectorRegion() {
		return this.sectorRegion;
	}

	public void setSectorRegion(String sectorRegion) {
		this.sectorRegion = sectorRegion;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getSectorPadre() {
		return this.sectorPadre;
	}

	public void setSectorPadre(String sectorPadre) {
		this.sectorPadre = sectorPadre;
	}

	public int getUltimo() {
		return ultimo;
	}

	public void setUltimo(int ultimo) {
		this.ultimo = ultimo;
	}
	
	@Override
	public String toString(){
		return String.valueOf(id);
	}

}
