package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewPermisosCatalogoMenuId generated by hbm2java
 */
public class ViewPermisosCatalogoMenuId implements java.io.Serializable {

	private int id;
	private String modulo;
	private String etiqueta;
	private Integer idCatalogoSecciones;
	private String url;
	private Integer prioridad;
	private int idPermiso;
	private Integer idUsuario;
	private Integer idCatalogoMenu;
	private Integer permiso;

	public ViewPermisosCatalogoMenuId() {
	}

	public ViewPermisosCatalogoMenuId(int id, int idPermiso) {
		this.id = id;
		this.idPermiso = idPermiso;
	}

	public ViewPermisosCatalogoMenuId(int id, String modulo, String etiqueta,
			Integer idCatalogoSecciones, String url, Integer prioridad,
			int idPermiso, Integer idUsuario, Integer idCatalogoMenu,
			Integer permiso) {
		this.id = id;
		this.modulo = modulo;
		this.etiqueta = etiqueta;
		this.idCatalogoSecciones = idCatalogoSecciones;
		this.url = url;
		this.prioridad = prioridad;
		this.idPermiso = idPermiso;
		this.idUsuario = idUsuario;
		this.idCatalogoMenu = idCatalogoMenu;
		this.permiso = permiso;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(String etiqueta) {
		this.etiqueta = etiqueta;
	}

	public Integer getIdCatalogoSecciones() {
		return this.idCatalogoSecciones;
	}

	public void setIdCatalogoSecciones(Integer idCatalogoSecciones) {
		this.idCatalogoSecciones = idCatalogoSecciones;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	public int getIdPermiso() {
		return this.idPermiso;
	}

	public void setIdPermiso(int idPermiso) {
		this.idPermiso = idPermiso;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getIdCatalogoMenu() {
		return this.idCatalogoMenu;
	}

	public void setIdCatalogoMenu(Integer idCatalogoMenu) {
		this.idCatalogoMenu = idCatalogoMenu;
	}

	public Integer getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Integer permiso) {
		this.permiso = permiso;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewPermisosCatalogoMenuId))
			return false;
		ViewPermisosCatalogoMenuId castOther = (ViewPermisosCatalogoMenuId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getModulo() == castOther.getModulo()) || (this
						.getModulo() != null && castOther.getModulo() != null && this
						.getModulo().equals(castOther.getModulo())))
				&& ((this.getEtiqueta() == castOther.getEtiqueta()) || (this
						.getEtiqueta() != null
						&& castOther.getEtiqueta() != null && this
						.getEtiqueta().equals(castOther.getEtiqueta())))
				&& ((this.getIdCatalogoSecciones() == castOther
						.getIdCatalogoSecciones()) || (this
						.getIdCatalogoSecciones() != null
						&& castOther.getIdCatalogoSecciones() != null && this
						.getIdCatalogoSecciones().equals(
								castOther.getIdCatalogoSecciones())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getPrioridad() == castOther.getPrioridad()) || (this
						.getPrioridad() != null
						&& castOther.getPrioridad() != null && this
						.getPrioridad().equals(castOther.getPrioridad())))
				&& (this.getIdPermiso() == castOther.getIdPermiso())
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
						.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this
						.getIdUsuario().equals(castOther.getIdUsuario())))
				&& ((this.getIdCatalogoMenu() == castOther.getIdCatalogoMenu()) || (this
						.getIdCatalogoMenu() != null
						&& castOther.getIdCatalogoMenu() != null && this
						.getIdCatalogoMenu().equals(
								castOther.getIdCatalogoMenu())))
				&& ((this.getPermiso() == castOther.getPermiso()) || (this
						.getPermiso() != null && castOther.getPermiso() != null && this
						.getPermiso().equals(castOther.getPermiso())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getModulo() == null ? 0 : this.getModulo().hashCode());
		result = 37 * result
				+ (getEtiqueta() == null ? 0 : this.getEtiqueta().hashCode());
		result = 37
				* result
				+ (getIdCatalogoSecciones() == null ? 0 : this
						.getIdCatalogoSecciones().hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result
				+ (getPrioridad() == null ? 0 : this.getPrioridad().hashCode());
		result = 37 * result + this.getIdPermiso();
		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37
				* result
				+ (getIdCatalogoMenu() == null ? 0 : this.getIdCatalogoMenu()
						.hashCode());
		result = 37 * result
				+ (getPermiso() == null ? 0 : this.getPermiso().hashCode());
		return result;
	}

}
