package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewEstudiantes generated by hbm2java
 */
public class ViewEstudiantes implements java.io.Serializable {

	private ViewEstudiantesId id;

	public ViewEstudiantes() {
	}

	public ViewEstudiantes(ViewEstudiantesId id) {
		this.id = id;
	}

	public ViewEstudiantesId getId() {
		return this.id;
	}

	public void setId(ViewEstudiantesId id) {
		this.id = id;
	}

}
