package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewLocalizacion generated by hbm2java
 */
public class ViewLocalizacion implements java.io.Serializable {

	private Integer id;
	private int idEstado;
	private String estado;
	private Integer idMunicipio;
	private String municipio;
	private Integer idRegion;
	private String region;
	private Integer idLocalidad;
	private String localidad;
	private Integer idCodigoPostal;
	private String cp;

	public ViewLocalizacion() {
	}

	public ViewLocalizacion(int idEstado, String estado) {
		this.idEstado = idEstado;
		this.estado = estado;
	}

	public ViewLocalizacion(Integer id, int idEstado, String estado,
			Integer idMunicipio, String municipio, Integer idRegion,
			String region, Integer idLocalidad, String localidad,
			Integer idCodigoPostal, String cp) {
		this.id = id;
		this.idEstado = idEstado;
		this.estado = estado;
		this.idMunicipio = idMunicipio;
		this.municipio = municipio;
		this.idRegion = idRegion;
		this.region = region;
		this.idLocalidad = idLocalidad;
		this.localidad = localidad;
		this.idCodigoPostal = idCodigoPostal;
		this.cp = cp;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(Integer idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public Integer getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(Integer idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Integer getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(Integer idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}


}
