package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Auditoria generated by hbm2java
 */
public class Auditoria implements java.io.Serializable {

	private Integer id;
	private String tabla;
	private int idTabla;
	private char movimiento;
	private Date fechaAlta;
	private int idUsuario;

	public Auditoria() {
	}

	public Auditoria(String tabla, int idTabla, char movimiento,
			Date fechaAlta, int idUsuario) {
		this.tabla = tabla;
		this.idTabla = idTabla;
		this.movimiento = movimiento;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	public int getIdTabla() {
		return this.idTabla;
	}

	public void setIdTabla(int idTabla) {
		this.idTabla = idTabla;
	}

	public char getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(char movimiento) {
		this.movimiento = movimiento;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
