package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewBoletosCompradores generated by hbm2java
 */
public class ViewBoletosCompradores implements java.io.Serializable {

	private ViewBoletosCompradoresId id;

	public ViewBoletosCompradores() {
	}

	public ViewBoletosCompradores(ViewBoletosCompradoresId id) {
		this.id = id;
	}

	public ViewBoletosCompradoresId getId() {
		return this.id;
	}

	public void setId(ViewBoletosCompradoresId id) {
		this.id = id;
	}

}
