package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * BoletosSaldoColEstudiantil generated by hbm2java
 */
public class BoletosSaldoColEstudiantil implements java.io.Serializable {

	private Integer id;
	private Integer idColaborador;
	private String nombre;
	private String sector;
	private String region;
	private String fc1b;
	private String fc1bAun;
	private String fc7b;
	private String fc2;
	private String fc2Aun;
	private String fc3;
	private String fc4;
	private String fc4b;
	private String fc4bVendidos;
	private Double sumaPagos;

	public BoletosSaldoColEstudiantil() {
	}

	public BoletosSaldoColEstudiantil(Integer idColaborador, String nombre,
			String sector, String region, String fc1b, String fc1bAun,
			String fc7b, String fc2, String fc2Aun, String fc3, String fc4,
			String fc4b, String fc4bVendidos, Double sumaPagos) {
		this.idColaborador = idColaborador;
		this.nombre = nombre;
		this.sector = sector;
		this.region = region;
		this.fc1b = fc1b;
		this.fc1bAun = fc1bAun;
		this.fc7b = fc7b;
		this.fc2 = fc2;
		this.fc2Aun = fc2Aun;
		this.fc3 = fc3;
		this.fc4 = fc4;
		this.fc4b = fc4b;
		this.fc4bVendidos = fc4bVendidos;
		this.sumaPagos = sumaPagos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(Integer idColaborador) {
		this.idColaborador = idColaborador;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getFc1b() {
		return this.fc1b;
	}

	public void setFc1b(String fc1b) {
		this.fc1b = fc1b;
	}

	public String getFc1bAun() {
		return this.fc1bAun;
	}

	public void setFc1bAun(String fc1bAun) {
		this.fc1bAun = fc1bAun;
	}

	public String getFc7b() {
		return this.fc7b;
	}

	public void setFc7b(String fc7b) {
		this.fc7b = fc7b;
	}

	public String getFc2() {
		return this.fc2;
	}

	public void setFc2(String fc2) {
		this.fc2 = fc2;
	}

	public String getFc2Aun() {
		return this.fc2Aun;
	}

	public void setFc2Aun(String fc2Aun) {
		this.fc2Aun = fc2Aun;
	}

	public String getFc3() {
		return this.fc3;
	}

	public void setFc3(String fc3) {
		this.fc3 = fc3;
	}

	public String getFc4() {
		return this.fc4;
	}

	public void setFc4(String fc4) {
		this.fc4 = fc4;
	}

	public String getFc4b() {
		return this.fc4b;
	}

	public void setFc4b(String fc4b) {
		this.fc4b = fc4b;
	}

	public String getFc4bVendidos() {
		return this.fc4bVendidos;
	}

	public void setFc4bVendidos(String fc4bVendidos) {
		this.fc4bVendidos = fc4bVendidos;
	}

	public Double getSumaPagos() {
		return this.sumaPagos;
	}

	public void setSumaPagos(Double sumaPagos) {
		this.sumaPagos = sumaPagos;
	}

}
