package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewBoletosCompradoresId generated by hbm2java
 */
public class ViewBoletosCompradoresId implements java.io.Serializable {

	private String boleto;
	private String cartera;
	private String tipoComprador;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String domicilio;
	private String colonia;
	private String codigoPostal;
	private String ciudad;
	private String nombre;
	private String telefono;
	private String celular;
	private String correo;
	private String sexo;
	private String exalumnouv;
	private Date fechaNacimiento;
	private String sorteo;
	private String usuario;
	private String fechaRegistro;
	private String nombreCompleto;
	private Integer idUsuario;

	public ViewBoletosCompradoresId() {
	}

	public ViewBoletosCompradoresId(String boleto, String nombres) {
		this.boleto = boleto;
		this.nombres = nombres;
	}

	public ViewBoletosCompradoresId(String boleto, String cartera,
			String tipoComprador, String nombres, String apellidoPaterno,
			String apellidoMaterno, String domicilio, String colonia,
			String codigoPostal, String ciudad, String nombre, String telefono,
			String celular, String correo, String sexo, String exalumnouv,
			Date fechaNacimiento, String sorteo, String usuario,
			String fechaRegistro, String nombreCompleto, Integer idUsuario) {
		this.boleto = boleto;
		this.cartera = cartera;
		this.tipoComprador = tipoComprador;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.domicilio = domicilio;
		this.colonia = colonia;
		this.codigoPostal = codigoPostal;
		this.ciudad = ciudad;
		this.nombre = nombre;
		this.telefono = telefono;
		this.celular = celular;
		this.correo = correo;
		this.sexo = sexo;
		this.exalumnouv = exalumnouv;
		this.fechaNacimiento = fechaNacimiento;
		this.sorteo = sorteo;
		this.usuario = usuario;
		this.fechaRegistro = fechaRegistro;
		this.nombreCompleto = nombreCompleto;
		this.idUsuario = idUsuario;
	}

	public String getBoleto() {
		return this.boleto;
	}

	public void setBoleto(String boleto) {
		this.boleto = boleto;
	}

	public String getCartera() {
		return this.cartera;
	}

	public void setCartera(String cartera) {
		this.cartera = cartera;
	}

	public String getTipoComprador() {
		return this.tipoComprador;
	}

	public void setTipoComprador(String tipoComprador) {
		this.tipoComprador = tipoComprador;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getExalumnouv() {
		return this.exalumnouv;
	}

	public void setExalumnouv(String exalumnouv) {
		this.exalumnouv = exalumnouv;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getSorteo() {
		return this.sorteo;
	}

	public void setSorteo(String sorteo) {
		this.sorteo = sorteo;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(String fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public void setNombreCompleto(String nombreCompleto) {
		this.nombreCompleto = nombreCompleto;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewBoletosCompradoresId))
			return false;
		ViewBoletosCompradoresId castOther = (ViewBoletosCompradoresId) other;

		return ((this.getBoleto() == castOther.getBoleto()) || (this
				.getBoleto() != null && castOther.getBoleto() != null && this
				.getBoleto().equals(castOther.getBoleto())))
				&& ((this.getCartera() == castOther.getCartera()) || (this
						.getCartera() != null && castOther.getCartera() != null && this
						.getCartera().equals(castOther.getCartera())))
				&& ((this.getTipoComprador() == castOther.getTipoComprador()) || (this
						.getTipoComprador() != null
						&& castOther.getTipoComprador() != null && this
						.getTipoComprador()
						.equals(castOther.getTipoComprador())))
				&& ((this.getNombres() == castOther.getNombres()) || (this
						.getNombres() != null && castOther.getNombres() != null && this
						.getNombres().equals(castOther.getNombres())))
				&& ((this.getApellidoPaterno() == castOther
						.getApellidoPaterno()) || (this.getApellidoPaterno() != null
						&& castOther.getApellidoPaterno() != null && this
						.getApellidoPaterno().equals(
								castOther.getApellidoPaterno())))
				&& ((this.getApellidoMaterno() == castOther
						.getApellidoMaterno()) || (this.getApellidoMaterno() != null
						&& castOther.getApellidoMaterno() != null && this
						.getApellidoMaterno().equals(
								castOther.getApellidoMaterno())))
				&& ((this.getDomicilio() == castOther.getDomicilio()) || (this
						.getDomicilio() != null
						&& castOther.getDomicilio() != null && this
						.getDomicilio().equals(castOther.getDomicilio())))
				&& ((this.getColonia() == castOther.getColonia()) || (this
						.getColonia() != null && castOther.getColonia() != null && this
						.getColonia().equals(castOther.getColonia())))
				&& ((this.getCodigoPostal() == castOther.getCodigoPostal()) || (this
						.getCodigoPostal() != null
						&& castOther.getCodigoPostal() != null && this
						.getCodigoPostal().equals(castOther.getCodigoPostal())))
				&& ((this.getCiudad() == castOther.getCiudad()) || (this
						.getCiudad() != null && castOther.getCiudad() != null && this
						.getCiudad().equals(castOther.getCiudad())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this
						.getTelefono() != null
						&& castOther.getTelefono() != null && this
						.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getCelular() == castOther.getCelular()) || (this
						.getCelular() != null && castOther.getCelular() != null && this
						.getCelular().equals(castOther.getCelular())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getSexo() == castOther.getSexo()) || (this.getSexo() != null
						&& castOther.getSexo() != null && this.getSexo()
						.equals(castOther.getSexo())))
				&& ((this.getExalumnouv() == castOther.getExalumnouv()) || (this
						.getExalumnouv() != null
						&& castOther.getExalumnouv() != null && this
						.getExalumnouv().equals(castOther.getExalumnouv())))
				&& ((this.getFechaNacimiento() == castOther
						.getFechaNacimiento()) || (this.getFechaNacimiento() != null
						&& castOther.getFechaNacimiento() != null && this
						.getFechaNacimiento().equals(
								castOther.getFechaNacimiento())))
				&& ((this.getSorteo() == castOther.getSorteo()) || (this
						.getSorteo() != null && castOther.getSorteo() != null && this
						.getSorteo().equals(castOther.getSorteo())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getFechaRegistro() == castOther.getFechaRegistro()) || (this
						.getFechaRegistro() != null
						&& castOther.getFechaRegistro() != null && this
						.getFechaRegistro()
						.equals(castOther.getFechaRegistro())))
				&& ((this.getNombreCompleto() == castOther.getNombreCompleto()) || (this
						.getNombreCompleto() != null
						&& castOther.getNombreCompleto() != null && this
						.getNombreCompleto().equals(
								castOther.getNombreCompleto())))
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
						.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this
						.getIdUsuario().equals(castOther.getIdUsuario())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBoleto() == null ? 0 : this.getBoleto().hashCode());
		result = 37 * result
				+ (getCartera() == null ? 0 : this.getCartera().hashCode());
		result = 37
				* result
				+ (getTipoComprador() == null ? 0 : this.getTipoComprador()
						.hashCode());
		result = 37 * result
				+ (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37
				* result
				+ (getApellidoPaterno() == null ? 0 : this.getApellidoPaterno()
						.hashCode());
		result = 37
				* result
				+ (getApellidoMaterno() == null ? 0 : this.getApellidoMaterno()
						.hashCode());
		result = 37 * result
				+ (getDomicilio() == null ? 0 : this.getDomicilio().hashCode());
		result = 37 * result
				+ (getColonia() == null ? 0 : this.getColonia().hashCode());
		result = 37
				* result
				+ (getCodigoPostal() == null ? 0 : this.getCodigoPostal()
						.hashCode());
		result = 37 * result
				+ (getCiudad() == null ? 0 : this.getCiudad().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result
				+ (getCelular() == null ? 0 : this.getCelular().hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result
				+ (getSexo() == null ? 0 : this.getSexo().hashCode());
		result = 37
				* result
				+ (getExalumnouv() == null ? 0 : this.getExalumnouv()
						.hashCode());
		result = 37
				* result
				+ (getFechaNacimiento() == null ? 0 : this.getFechaNacimiento()
						.hashCode());
		result = 37 * result
				+ (getSorteo() == null ? 0 : this.getSorteo().hashCode());
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37
				* result
				+ (getFechaRegistro() == null ? 0 : this.getFechaRegistro()
						.hashCode());
		result = 37
				* result
				+ (getNombreCompleto() == null ? 0 : this.getNombreCompleto()
						.hashCode());
		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		return result;
	}

}
