package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Regiones generated by hbm2java
 */
public class Regiones implements java.io.Serializable {

	private Integer id;
	private String region;
	private String nombreCorto;
	private int idEstado;
	private char estatus;

	public Regiones() {
	}

	public Regiones(String region, String nombreCorto, int idEstado,
			char estatus) {
		this.region = region;
		this.nombreCorto = nombreCorto;
		this.idEstado = idEstado;
		this.estatus = estatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getNombreCorto() {
		return this.nombreCorto;
	}

	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
