package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * SorteoColaboradoresVer generated by hbm2java
 */
public class SorteoColaboradoresVer implements java.io.Serializable {

	private Integer id;
	private int idBoleto;
	private int estatus;
	private int idPremio;
	private String boleto;
	private String colaborador;
	private Integer premio;
	private String tipoSector;
	private String sector;
	private Integer idRegion;
	private Integer idSorteo;
	private Integer contacto;
	private String aclaracion;
	private String donde;
	private String debe;
	private String celular;
	private String correo;
	private String nota;

	public SorteoColaboradoresVer() {
	}

	public SorteoColaboradoresVer(int idBoleto, int estatus, int idPremio) {
		this.idBoleto = idBoleto;
		this.estatus = estatus;
		this.idPremio = idPremio;
	}

	public SorteoColaboradoresVer(int idBoleto, int estatus, int idPremio,
			String boleto, String colaborador, Integer premio,
			String tipoSector, String sector, Integer idRegion,
			Integer idSorteo, Integer contacto, String aclaracion,
			String donde, String debe, String celular, String correo,
			String nota) {
		this.idBoleto = idBoleto;
		this.estatus = estatus;
		this.idPremio = idPremio;
		this.boleto = boleto;
		this.colaborador = colaborador;
		this.premio = premio;
		this.tipoSector = tipoSector;
		this.sector = sector;
		this.idRegion = idRegion;
		this.idSorteo = idSorteo;
		this.contacto = contacto;
		this.aclaracion = aclaracion;
		this.donde = donde;
		this.debe = debe;
		this.celular = celular;
		this.correo = correo;
		this.nota = nota;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public int getIdPremio() {
		return this.idPremio;
	}

	public void setIdPremio(int idPremio) {
		this.idPremio = idPremio;
	}

	public String getBoleto() {
		return this.boleto;
	}

	public void setBoleto(String boleto) {
		this.boleto = boleto;
	}

	public String getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(String colaborador) {
		this.colaborador = colaborador;
	}

	public Integer getPremio() {
		return this.premio;
	}

	public void setPremio(Integer premio) {
		this.premio = premio;
	}

	public String getTipoSector() {
		return this.tipoSector;
	}

	public void setTipoSector(String tipoSector) {
		this.tipoSector = tipoSector;
	}

	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

	public Integer getIdSorteo() {
		return this.idSorteo;
	}

	public void setIdSorteo(Integer idSorteo) {
		this.idSorteo = idSorteo;
	}

	public Integer getContacto() {
		return this.contacto;
	}

	public void setContacto(Integer contacto) {
		this.contacto = contacto;
	}

	public String getAclaracion() {
		return this.aclaracion;
	}

	public void setAclaracion(String aclaracion) {
		this.aclaracion = aclaracion;
	}

	public String getDonde() {
		return this.donde;
	}

	public void setDonde(String donde) {
		this.donde = donde;
	}

	public String getDebe() {
		return this.debe;
	}

	public void setDebe(String debe) {
		this.debe = debe;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

}
