package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BoletosElectronicos generated by hbm2java
 */
public class BoletosElectronicos implements java.io.Serializable {

	private Integer id;
	private int idColaborador;
	private int idPromocion;
	private String numeroBoleto;
	private Integer tipo;
	private Integer estatus;
	private Date fechaAlta;
	private int idUsuario;

	public BoletosElectronicos() {
	}

	public BoletosElectronicos(int idColaborador, int idPromocion,
			String numeroBoleto, Date fechaAlta, int idUsuario) {
		this.idColaborador = idColaborador;
		this.idPromocion = idPromocion;
		this.numeroBoleto = numeroBoleto;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
	}

	public BoletosElectronicos(int idColaborador, int idPromocion,
			String numeroBoleto, Integer tipo, Integer estatus, Date fechaAlta,
			int idUsuario) {
		this.idColaborador = idColaborador;
		this.idPromocion = idPromocion;
		this.numeroBoleto = numeroBoleto;
		this.tipo = tipo;
		this.estatus = estatus;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(int idColaborador) {
		this.idColaborador = idColaborador;
	}

	public int getIdPromocion() {
		return this.idPromocion;
	}

	public void setIdPromocion(int idPromocion) {
		this.idPromocion = idPromocion;
	}

	public String getNumeroBoleto() {
		return this.numeroBoleto;
	}

	public void setNumeroBoleto(String numeroBoleto) {
		this.numeroBoleto = numeroBoleto;
	}

	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
