package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewPromotoresId generated by hbm2java
 */
public class ViewPromotoresId implements java.io.Serializable {

	private int id;
	private String clave;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private Date fechaNacimiento;
	private String calle;
	private String numeroInterior;
	private String numeroExterior;
	private int idCodigoPostal;
	private int idRegion;
	private int idEstado;
	private int idMunicipio;
	private Integer idLocalidad;
	private Integer idSector;
	private String tipo;
	private String telefonoCasa;
	private String telefonoOficina;
	private String celular;
	private String correo;
	private String rfc;
	private Date fechaAlta;
	private int idUsuario;
	private int estatus;
	private String observaciones;
	private Integer meta;
	private Double comision;
	private Integer tipoEnlace;
	private Integer ofiInsDepFac;
	private String carrera;
	private String matricula;
	private Integer numeroPersonal;
	private Integer idPromotorpadre;
	private String nombre;
	private String tipoEjecutivo;
	private String estado;
	private String localidad;
	private String municipio;
	private String cp;
	private String region;

	public ViewPromotoresId() {
	}

	public ViewPromotoresId(int id, String clave, String nombres,
			String apellidoPaterno, Date fechaNacimiento, String calle,
			String numeroExterior, int idCodigoPostal, int idRegion,
			int idEstado, int idMunicipio, String tipo, String rfc,
			Date fechaAlta, int idUsuario, int estatus, String tipoEjecutivo) {
		this.id = id;
		this.clave = clave;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.fechaNacimiento = fechaNacimiento;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.idCodigoPostal = idCodigoPostal;
		this.idRegion = idRegion;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.tipo = tipo;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.estatus = estatus;
		this.tipoEjecutivo = tipoEjecutivo;
	}

	public ViewPromotoresId(int id, String clave, String nombres,
			String apellidoPaterno, String apellidoMaterno,
			Date fechaNacimiento, String calle, String numeroInterior,
			String numeroExterior, int idCodigoPostal, int idRegion,
			int idEstado, int idMunicipio, Integer idLocalidad,
			Integer idSector, String tipo, String telefonoCasa,
			String telefonoOficina, String celular, String correo, String rfc,
			Date fechaAlta, int idUsuario, int estatus, String observaciones,
			Integer meta, Double comision, Integer tipoEnlace,
			Integer ofiInsDepFac, String carrera, String matricula,
			Integer numeroPersonal, Integer idPromotorpadre, String nombre,
			String tipoEjecutivo, String estado, String localidad,
			String municipio, String cp, String region) {
		this.id = id;
		this.clave = clave;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.fechaNacimiento = fechaNacimiento;
		this.calle = calle;
		this.numeroInterior = numeroInterior;
		this.numeroExterior = numeroExterior;
		this.idCodigoPostal = idCodigoPostal;
		this.idRegion = idRegion;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idLocalidad = idLocalidad;
		this.idSector = idSector;
		this.tipo = tipo;
		this.telefonoCasa = telefonoCasa;
		this.telefonoOficina = telefonoOficina;
		this.celular = celular;
		this.correo = correo;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.estatus = estatus;
		this.observaciones = observaciones;
		this.meta = meta;
		this.comision = comision;
		this.tipoEnlace = tipoEnlace;
		this.ofiInsDepFac = ofiInsDepFac;
		this.carrera = carrera;
		this.matricula = matricula;
		this.numeroPersonal = numeroPersonal;
		this.idPromotorpadre = idPromotorpadre;
		this.nombre = nombre;
		this.tipoEjecutivo = tipoEjecutivo;
		this.estado = estado;
		this.localidad = localidad;
		this.municipio = municipio;
		this.cp = cp;
		this.region = region;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	public int getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(int idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Integer getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(Integer idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Integer getIdSector() {
		return this.idSector;
	}

	public void setIdSector(Integer idSector) {
		this.idSector = idSector;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		this.telefonoOficina = telefonoOficina;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getMeta() {
		return this.meta;
	}

	public void setMeta(Integer meta) {
		this.meta = meta;
	}

	public Double getComision() {
		return this.comision;
	}

	public void setComision(Double comision) {
		this.comision = comision;
	}

	public Integer getTipoEnlace() {
		return this.tipoEnlace;
	}

	public void setTipoEnlace(Integer tipoEnlace) {
		this.tipoEnlace = tipoEnlace;
	}

	public Integer getOfiInsDepFac() {
		return this.ofiInsDepFac;
	}

	public void setOfiInsDepFac(Integer ofiInsDepFac) {
		this.ofiInsDepFac = ofiInsDepFac;
	}

	public String getCarrera() {
		return this.carrera;
	}

	public void setCarrera(String carrera) {
		this.carrera = carrera;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public Integer getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(Integer numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	public Integer getIdPromotorpadre() {
		return this.idPromotorpadre;
	}

	public void setIdPromotorpadre(Integer idPromotorpadre) {
		this.idPromotorpadre = idPromotorpadre;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoEjecutivo() {
		return this.tipoEjecutivo;
	}

	public void setTipoEjecutivo(String tipoEjecutivo) {
		this.tipoEjecutivo = tipoEjecutivo;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewPromotoresId))
			return false;
		ViewPromotoresId castOther = (ViewPromotoresId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getClave() == castOther.getClave()) || (this
						.getClave() != null && castOther.getClave() != null && this
						.getClave().equals(castOther.getClave())))
				&& ((this.getNombres() == castOther.getNombres()) || (this
						.getNombres() != null && castOther.getNombres() != null && this
						.getNombres().equals(castOther.getNombres())))
				&& ((this.getApellidoPaterno() == castOther
						.getApellidoPaterno()) || (this.getApellidoPaterno() != null
						&& castOther.getApellidoPaterno() != null && this
						.getApellidoPaterno().equals(
								castOther.getApellidoPaterno())))
				&& ((this.getApellidoMaterno() == castOther
						.getApellidoMaterno()) || (this.getApellidoMaterno() != null
						&& castOther.getApellidoMaterno() != null && this
						.getApellidoMaterno().equals(
								castOther.getApellidoMaterno())))
				&& ((this.getFechaNacimiento() == castOther
						.getFechaNacimiento()) || (this.getFechaNacimiento() != null
						&& castOther.getFechaNacimiento() != null && this
						.getFechaNacimiento().equals(
								castOther.getFechaNacimiento())))
				&& ((this.getCalle() == castOther.getCalle()) || (this
						.getCalle() != null && castOther.getCalle() != null && this
						.getCalle().equals(castOther.getCalle())))
				&& ((this.getNumeroInterior() == castOther.getNumeroInterior()) || (this
						.getNumeroInterior() != null
						&& castOther.getNumeroInterior() != null && this
						.getNumeroInterior().equals(
								castOther.getNumeroInterior())))
				&& ((this.getNumeroExterior() == castOther.getNumeroExterior()) || (this
						.getNumeroExterior() != null
						&& castOther.getNumeroExterior() != null && this
						.getNumeroExterior().equals(
								castOther.getNumeroExterior())))
				&& (this.getIdCodigoPostal() == castOther.getIdCodigoPostal())
				&& (this.getIdRegion() == castOther.getIdRegion())
				&& (this.getIdEstado() == castOther.getIdEstado())
				&& (this.getIdMunicipio() == castOther.getIdMunicipio())
				&& ((this.getIdLocalidad() == castOther.getIdLocalidad()) || (this
						.getIdLocalidad() != null
						&& castOther.getIdLocalidad() != null && this
						.getIdLocalidad().equals(castOther.getIdLocalidad())))
				&& ((this.getIdSector() == castOther.getIdSector()) || (this
						.getIdSector() != null
						&& castOther.getIdSector() != null && this
						.getIdSector().equals(castOther.getIdSector())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())))
				&& ((this.getTelefonoCasa() == castOther.getTelefonoCasa()) || (this
						.getTelefonoCasa() != null
						&& castOther.getTelefonoCasa() != null && this
						.getTelefonoCasa().equals(castOther.getTelefonoCasa())))
				&& ((this.getTelefonoOficina() == castOther
						.getTelefonoOficina()) || (this.getTelefonoOficina() != null
						&& castOther.getTelefonoOficina() != null && this
						.getTelefonoOficina().equals(
								castOther.getTelefonoOficina())))
				&& ((this.getCelular() == castOther.getCelular()) || (this
						.getCelular() != null && castOther.getCelular() != null && this
						.getCelular().equals(castOther.getCelular())))
				&& ((this.getCorreo() == castOther.getCorreo()) || (this
						.getCorreo() != null && castOther.getCorreo() != null && this
						.getCorreo().equals(castOther.getCorreo())))
				&& ((this.getRfc() == castOther.getRfc()) || (this.getRfc() != null
						&& castOther.getRfc() != null && this.getRfc().equals(
						castOther.getRfc())))
				&& ((this.getFechaAlta() == castOther.getFechaAlta()) || (this
						.getFechaAlta() != null
						&& castOther.getFechaAlta() != null && this
						.getFechaAlta().equals(castOther.getFechaAlta())))
				&& (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getEstatus() == castOther.getEstatus())
				&& ((this.getObservaciones() == castOther.getObservaciones()) || (this
						.getObservaciones() != null
						&& castOther.getObservaciones() != null && this
						.getObservaciones()
						.equals(castOther.getObservaciones())))
				&& ((this.getMeta() == castOther.getMeta()) || (this.getMeta() != null
						&& castOther.getMeta() != null && this.getMeta()
						.equals(castOther.getMeta())))
				&& ((this.getComision() == castOther.getComision()) || (this
						.getComision() != null
						&& castOther.getComision() != null && this
						.getComision().equals(castOther.getComision())))
				&& ((this.getTipoEnlace() == castOther.getTipoEnlace()) || (this
						.getTipoEnlace() != null
						&& castOther.getTipoEnlace() != null && this
						.getTipoEnlace().equals(castOther.getTipoEnlace())))
				&& ((this.getOfiInsDepFac() == castOther.getOfiInsDepFac()) || (this
						.getOfiInsDepFac() != null
						&& castOther.getOfiInsDepFac() != null && this
						.getOfiInsDepFac().equals(castOther.getOfiInsDepFac())))
				&& ((this.getCarrera() == castOther.getCarrera()) || (this
						.getCarrera() != null && castOther.getCarrera() != null && this
						.getCarrera().equals(castOther.getCarrera())))
				&& ((this.getMatricula() == castOther.getMatricula()) || (this
						.getMatricula() != null
						&& castOther.getMatricula() != null && this
						.getMatricula().equals(castOther.getMatricula())))
				&& ((this.getNumeroPersonal() == castOther.getNumeroPersonal()) || (this
						.getNumeroPersonal() != null
						&& castOther.getNumeroPersonal() != null && this
						.getNumeroPersonal().equals(
								castOther.getNumeroPersonal())))
				&& ((this.getIdPromotorpadre() == castOther
						.getIdPromotorpadre()) || (this.getIdPromotorpadre() != null
						&& castOther.getIdPromotorpadre() != null && this
						.getIdPromotorpadre().equals(
								castOther.getIdPromotorpadre())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getTipoEjecutivo() == castOther.getTipoEjecutivo()) || (this
						.getTipoEjecutivo() != null
						&& castOther.getTipoEjecutivo() != null && this
						.getTipoEjecutivo()
						.equals(castOther.getTipoEjecutivo())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getLocalidad() == castOther.getLocalidad()) || (this
						.getLocalidad() != null
						&& castOther.getLocalidad() != null && this
						.getLocalidad().equals(castOther.getLocalidad())))
				&& ((this.getMunicipio() == castOther.getMunicipio()) || (this
						.getMunicipio() != null
						&& castOther.getMunicipio() != null && this
						.getMunicipio().equals(castOther.getMunicipio())))
				&& ((this.getCp() == castOther.getCp()) || (this.getCp() != null
						&& castOther.getCp() != null && this.getCp().equals(
						castOther.getCp())))
				&& ((this.getRegion() == castOther.getRegion()) || (this
						.getRegion() != null && castOther.getRegion() != null && this
						.getRegion().equals(castOther.getRegion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getClave() == null ? 0 : this.getClave().hashCode());
		result = 37 * result
				+ (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37
				* result
				+ (getApellidoPaterno() == null ? 0 : this.getApellidoPaterno()
						.hashCode());
		result = 37
				* result
				+ (getApellidoMaterno() == null ? 0 : this.getApellidoMaterno()
						.hashCode());
		result = 37
				* result
				+ (getFechaNacimiento() == null ? 0 : this.getFechaNacimiento()
						.hashCode());
		result = 37 * result
				+ (getCalle() == null ? 0 : this.getCalle().hashCode());
		result = 37
				* result
				+ (getNumeroInterior() == null ? 0 : this.getNumeroInterior()
						.hashCode());
		result = 37
				* result
				+ (getNumeroExterior() == null ? 0 : this.getNumeroExterior()
						.hashCode());
		result = 37 * result + this.getIdCodigoPostal();
		result = 37 * result + this.getIdRegion();
		result = 37 * result + this.getIdEstado();
		result = 37 * result + this.getIdMunicipio();
		result = 37
				* result
				+ (getIdLocalidad() == null ? 0 : this.getIdLocalidad()
						.hashCode());
		result = 37 * result
				+ (getIdSector() == null ? 0 : this.getIdSector().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37
				* result
				+ (getTelefonoCasa() == null ? 0 : this.getTelefonoCasa()
						.hashCode());
		result = 37
				* result
				+ (getTelefonoOficina() == null ? 0 : this.getTelefonoOficina()
						.hashCode());
		result = 37 * result
				+ (getCelular() == null ? 0 : this.getCelular().hashCode());
		result = 37 * result
				+ (getCorreo() == null ? 0 : this.getCorreo().hashCode());
		result = 37 * result
				+ (getRfc() == null ? 0 : this.getRfc().hashCode());
		result = 37 * result
				+ (getFechaAlta() == null ? 0 : this.getFechaAlta().hashCode());
		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getEstatus();
		result = 37
				* result
				+ (getObservaciones() == null ? 0 : this.getObservaciones()
						.hashCode());
		result = 37 * result
				+ (getMeta() == null ? 0 : this.getMeta().hashCode());
		result = 37 * result
				+ (getComision() == null ? 0 : this.getComision().hashCode());
		result = 37
				* result
				+ (getTipoEnlace() == null ? 0 : this.getTipoEnlace()
						.hashCode());
		result = 37
				* result
				+ (getOfiInsDepFac() == null ? 0 : this.getOfiInsDepFac()
						.hashCode());
		result = 37 * result
				+ (getCarrera() == null ? 0 : this.getCarrera().hashCode());
		result = 37 * result
				+ (getMatricula() == null ? 0 : this.getMatricula().hashCode());
		result = 37
				* result
				+ (getNumeroPersonal() == null ? 0 : this.getNumeroPersonal()
						.hashCode());
		result = 37
				* result
				+ (getIdPromotorpadre() == null ? 0 : this.getIdPromotorpadre()
						.hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37
				* result
				+ (getTipoEjecutivo() == null ? 0 : this.getTipoEjecutivo()
						.hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37 * result
				+ (getLocalidad() == null ? 0 : this.getLocalidad().hashCode());
		result = 37 * result
				+ (getMunicipio() == null ? 0 : this.getMunicipio().hashCode());
		result = 37 * result + (getCp() == null ? 0 : this.getCp().hashCode());
		result = 37 * result
				+ (getRegion() == null ? 0 : this.getRegion().hashCode());
		return result;
	}

}
