package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * SorteoMagno generated by hbm2java
 */
public class SorteoMagno implements java.io.Serializable {

	private Integer id;
	private int idBoleto;
	private int idCartera;
	private Character ubicacion;
	private Integer idColaborador;
	private Integer idEjecutivo;
	private Integer idFc2;
	private Integer idPremio;
	private Integer idPremioAsignado;
	private String nombreGanador;
	private String calleGanador;
	private String ciudadGanador;
	private String telefonoGanador;
	private Integer estatus;
	private String boleto;
	private String cartera;
	private String nombreColaborador;
	private Integer folioFc2;
	private Integer premio;
	private Integer asignado;
	private String numExtGanador;
	private String numIntGanador;
	private String cpGanador;
	private String coloniaGanador;
	private Integer contacto;
	private String region;
	private String aclaracion;
	private String donde;
	private String debe;
	private String correo;
	private String nota;
	private String celular;
	private String aclaracionAs;
	private String dondeAs;
	private String debeAs;
	private String notaAs;

	public SorteoMagno() {
	}

	public SorteoMagno(int idBoleto, int idCartera) {
		this.idBoleto = idBoleto;
		this.idCartera = idCartera;
	}

	public SorteoMagno(int idBoleto, int idCartera, Character ubicacion,
			Integer idColaborador, Integer idEjecutivo, Integer idFc2,
			Integer idPremio, Integer idPremioAsignado, String nombreGanador,
			String calleGanador, String ciudadGanador, String telefonoGanador,
			Integer estatus, String boleto, String cartera,
			String nombreColaborador, Integer folioFc2, Integer premio,
			Integer asignado, String numExtGanador, String numIntGanador,
			String cpGanador, String coloniaGanador, Integer contacto,
			String region, String aclaracion, String donde, String debe,
			String correo, String nota, String celular, String aclaracionAs,
			String dondeAs, String debeAs, String notaAs) {
		this.idBoleto = idBoleto;
		this.idCartera = idCartera;
		this.ubicacion = ubicacion;
		this.idColaborador = idColaborador;
		this.idEjecutivo = idEjecutivo;
		this.idFc2 = idFc2;
		this.idPremio = idPremio;
		this.idPremioAsignado = idPremioAsignado;
		this.nombreGanador = nombreGanador;
		this.calleGanador = calleGanador;
		this.ciudadGanador = ciudadGanador;
		this.telefonoGanador = telefonoGanador;
		this.estatus = estatus;
		this.boleto = boleto;
		this.cartera = cartera;
		this.nombreColaborador = nombreColaborador;
		this.folioFc2 = folioFc2;
		this.premio = premio;
		this.asignado = asignado;
		this.numExtGanador = numExtGanador;
		this.numIntGanador = numIntGanador;
		this.cpGanador = cpGanador;
		this.coloniaGanador = coloniaGanador;
		this.contacto = contacto;
		this.region = region;
		this.aclaracion = aclaracion;
		this.donde = donde;
		this.debe = debe;
		this.correo = correo;
		this.nota = nota;
		this.celular = celular;
		this.aclaracionAs = aclaracionAs;
		this.dondeAs = dondeAs;
		this.debeAs = debeAs;
		this.notaAs = notaAs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

	public int getIdCartera() {
		return this.idCartera;
	}

	public void setIdCartera(int idCartera) {
		this.idCartera = idCartera;
	}

	public Character getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Character ubicacion) {
		this.ubicacion = ubicacion;
	}

	public Integer getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(Integer idColaborador) {
		this.idColaborador = idColaborador;
	}

	public Integer getIdEjecutivo() {
		return this.idEjecutivo;
	}

	public void setIdEjecutivo(Integer idEjecutivo) {
		this.idEjecutivo = idEjecutivo;
	}

	public Integer getIdFc2() {
		return this.idFc2;
	}

	public void setIdFc2(Integer idFc2) {
		this.idFc2 = idFc2;
	}

	public Integer getIdPremio() {
		return this.idPremio;
	}

	public void setIdPremio(Integer idPremio) {
		this.idPremio = idPremio;
	}

	public Integer getIdPremioAsignado() {
		return this.idPremioAsignado;
	}

	public void setIdPremioAsignado(Integer idPremioAsignado) {
		this.idPremioAsignado = idPremioAsignado;
	}

	public String getNombreGanador() {
		return this.nombreGanador;
	}

	public void setNombreGanador(String nombreGanador) {
		this.nombreGanador = nombreGanador;
	}

	public String getCalleGanador() {
		return this.calleGanador;
	}

	public void setCalleGanador(String calleGanador) {
		this.calleGanador = calleGanador;
	}

	public String getCiudadGanador() {
		return this.ciudadGanador;
	}

	public void setCiudadGanador(String ciudadGanador) {
		this.ciudadGanador = ciudadGanador;
	}

	public String getTelefonoGanador() {
		return this.telefonoGanador;
	}

	public void setTelefonoGanador(String telefonoGanador) {
		this.telefonoGanador = telefonoGanador;
	}

	public Integer getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Integer estatus) {
		this.estatus = estatus;
	}

	public String getBoleto() {
		return this.boleto;
	}

	public void setBoleto(String boleto) {
		this.boleto = boleto;
	}

	public String getCartera() {
		return this.cartera;
	}

	public void setCartera(String cartera) {
		this.cartera = cartera;
	}

	public String getNombreColaborador() {
		return this.nombreColaborador;
	}

	public void setNombreColaborador(String nombreColaborador) {
		this.nombreColaborador = nombreColaborador;
	}

	public Integer getFolioFc2() {
		return this.folioFc2;
	}

	public void setFolioFc2(Integer folioFc2) {
		this.folioFc2 = folioFc2;
	}

	public Integer getPremio() {
		return this.premio;
	}

	public void setPremio(Integer premio) {
		this.premio = premio;
	}

	public Integer getAsignado() {
		return this.asignado;
	}

	public void setAsignado(Integer asignado) {
		this.asignado = asignado;
	}

	public String getNumExtGanador() {
		return this.numExtGanador;
	}

	public void setNumExtGanador(String numExtGanador) {
		this.numExtGanador = numExtGanador;
	}

	public String getNumIntGanador() {
		return this.numIntGanador;
	}

	public void setNumIntGanador(String numIntGanador) {
		this.numIntGanador = numIntGanador;
	}

	public String getCpGanador() {
		return this.cpGanador;
	}

	public void setCpGanador(String cpGanador) {
		this.cpGanador = cpGanador;
	}

	public String getColoniaGanador() {
		return this.coloniaGanador;
	}

	public void setColoniaGanador(String coloniaGanador) {
		this.coloniaGanador = coloniaGanador;
	}

	public Integer getContacto() {
		return this.contacto;
	}

	public void setContacto(Integer contacto) {
		this.contacto = contacto;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getAclaracion() {
		return this.aclaracion;
	}

	public void setAclaracion(String aclaracion) {
		this.aclaracion = aclaracion;
	}

	public String getDonde() {
		return this.donde;
	}

	public void setDonde(String donde) {
		this.donde = donde;
	}

	public String getDebe() {
		return this.debe;
	}

	public void setDebe(String debe) {
		this.debe = debe;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getNota() {
		return this.nota;
	}

	public void setNota(String nota) {
		this.nota = nota;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getAclaracionAs() {
		return this.aclaracionAs;
	}

	public void setAclaracionAs(String aclaracionAs) {
		this.aclaracionAs = aclaracionAs;
	}

	public String getDondeAs() {
		return this.dondeAs;
	}

	public void setDondeAs(String dondeAs) {
		this.dondeAs = dondeAs;
	}

	public String getDebeAs() {
		return this.debeAs;
	}

	public void setDebeAs(String debeAs) {
		this.debeAs = debeAs;
	}

	public String getNotaAs() {
		return this.notaAs;
	}

	public void setNotaAs(String notaAs) {
		this.notaAs = notaAs;
	}

}
