package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * BoletosEjecutivo generated by hbm2java
 */
public class BoletosEjecutivo implements java.io.Serializable {

	private Integer id;
	private Integer idPromotor;
	private String clavePromotor;
	private String nombre;
	private String fc1;
	private String fc7;
	private String fc2;
	private String fc3;
	private String fc4;
	private String fc4b;
	private String fc4bVendidos;
	private Double sumaPagos;

	public BoletosEjecutivo() {
	}

	public BoletosEjecutivo(Integer idPromotor, String clavePromotor,
			String nombre, String fc1, String fc7, String fc2, String fc3,
			String fc4, String fc4b, String fc4bVendidos, Double sumaPagos) {
		this.idPromotor = idPromotor;
		this.clavePromotor = clavePromotor;
		this.nombre = nombre;
		this.fc1 = fc1;
		this.fc7 = fc7;
		this.fc2 = fc2;
		this.fc3 = fc3;
		this.fc4 = fc4;
		this.fc4b = fc4b;
		this.fc4bVendidos = fc4bVendidos;
		this.sumaPagos = sumaPagos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(Integer idPromotor) {
		this.idPromotor = idPromotor;
	}

	public String getClavePromotor() {
		return this.clavePromotor;
	}

	public void setClavePromotor(String clavePromotor) {
		this.clavePromotor = clavePromotor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFc1() {
		return this.fc1;
	}

	public void setFc1(String fc1) {
		this.fc1 = fc1;
	}

	public String getFc7() {
		return this.fc7;
	}

	public void setFc7(String fc7) {
		this.fc7 = fc7;
	}

	public String getFc2() {
		return this.fc2;
	}

	public void setFc2(String fc2) {
		this.fc2 = fc2;
	}

	public String getFc3() {
		return this.fc3;
	}

	public void setFc3(String fc3) {
		this.fc3 = fc3;
	}

	public String getFc4() {
		return this.fc4;
	}

	public void setFc4(String fc4) {
		this.fc4 = fc4;
	}

	public String getFc4b() {
		return this.fc4b;
	}

	public void setFc4b(String fc4b) {
		this.fc4b = fc4b;
	}

	public String getFc4bVendidos() {
		return this.fc4bVendidos;
	}

	public void setFc4bVendidos(String fc4bVendidos) {
		this.fc4bVendidos = fc4bVendidos;
	}

	public Double getSumaPagos() {
		return this.sumaPagos;
	}

	public void setSumaPagos(Double sumaPagos) {
		this.sumaPagos = sumaPagos;
	}

}
