package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Permisos generated by hbm2java
 */
public class Permisos implements java.io.Serializable {

	private Integer id;
	private Integer idUsuario;
	private Integer idCatalogoMenu;
	private Integer permiso;

	public Permisos() {
	}

	public Permisos(Integer idUsuario, Integer idCatalogoMenu, Integer permiso) {
		this.idUsuario = idUsuario;
		this.idCatalogoMenu = idCatalogoMenu;
		this.permiso = permiso;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Integer getIdCatalogoMenu() {
		return this.idCatalogoMenu;
	}

	public void setIdCatalogoMenu(Integer idCatalogoMenu) {
		this.idCatalogoMenu = idCatalogoMenu;
	}

	public Integer getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Integer permiso) {
		this.permiso = permiso;
	}

}
