package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Retornos generated by hbm2java
 */
public class Retornos implements java.io.Serializable {

	private Integer id;
	private Integer idColaborador;
	private String tipoRetorno;
	private Date fechaRetorno;
	private String folio;
	private Date fechaAlta;
	private int idUsuario;
	private int idFc2;

	public Retornos() {
	}

	public Retornos(String tipoRetorno, Date fechaRetorno, String folio,
			Date fechaAlta, int idUsuario, int idFc2) {
		this.tipoRetorno = tipoRetorno;
		this.fechaRetorno = fechaRetorno;
		this.folio = folio;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.idFc2 = idFc2;
	}

	public Retornos(Integer idColaborador, String tipoRetorno,
			Date fechaRetorno, String folio, Date fechaAlta, int idUsuario,
			int idFc2) {
		this.idColaborador = idColaborador;
		this.tipoRetorno = tipoRetorno;
		this.fechaRetorno = fechaRetorno;
		this.folio = folio;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.idFc2 = idFc2;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(Integer idColaborador) {
		this.idColaborador = idColaborador;
	}

	public String getTipoRetorno() {
		return this.tipoRetorno;
	}

	public void setTipoRetorno(String tipoRetorno) {
		this.tipoRetorno = tipoRetorno;
	}

	public Date getFechaRetorno() {
		return this.fechaRetorno;
	}

	public void setFechaRetorno(Date fechaRetorno) {
		this.fechaRetorno = fechaRetorno;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdFc2() {
		return this.idFc2;
	}

	public void setIdFc2(int idFc2) {
		this.idFc2 = idFc2;
	}

}
