package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc7bBoletos generated by hbm2java
 */
public class Fc7bBoletos implements java.io.Serializable {

	private Integer id;
	private Integer idFc7bCarteras;
	private Integer idBoleto;

	public Fc7bBoletos() {
	}

	public Fc7bBoletos(Integer idFc7bCarteras, Integer idBoleto) {
		this.idFc7bCarteras = idFc7bCarteras;
		this.idBoleto = idBoleto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getIdFc7bCarteras() {
		return this.idFc7bCarteras;
	}

	public void setIdFc7bCarteras(Integer idFc7bCarteras) {
		this.idFc7bCarteras = idFc7bCarteras;
	}

	public Integer getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(Integer idBoleto) {
		this.idBoleto = idBoleto;
	}

}
