package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PromotoresHistorial generated by hbm2java
 */
public class PromotoresHistorial implements java.io.Serializable {

	private Integer id;
	private String clave;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private Date fechaNacimiento;
	private String calle;
	private String numeroInterior;
	private String numeroExterior;
	private int idCodigoPostal;
	private int idRegion;
	private int idEstado;
	private int idMunicipio;
	private Integer idLocalidad;
	private Integer idSector;
	private String tipo;
	private String telefonoCasa;
	private String telefonoOficina;
	private String celular;
	private String correo;
	private String rfc;
	private Date fechaAlta;
	private int idUsuario;
	private int estatus;
	private String observaciones;
	private Integer meta;
	private Integer comision;
	private Integer tipoEnlace;
	private Integer ofiInsDepFac;
	private String carrera;
	private String matricula;
	private Integer numeroPersonal;
	private Integer idPromotorpadre;
	private Integer existe;
	private Integer replica;

	public PromotoresHistorial() {
	}

	public PromotoresHistorial(String clave, String nombres,
			String apellidoPaterno, Date fechaNacimiento, String calle,
			String numeroExterior, int idCodigoPostal, int idRegion,
			int idEstado, int idMunicipio, String tipo, String rfc,
			Date fechaAlta, int idUsuario, int estatus) {
		this.clave = clave;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.fechaNacimiento = fechaNacimiento;
		this.calle = calle;
		this.numeroExterior = numeroExterior;
		this.idCodigoPostal = idCodigoPostal;
		this.idRegion = idRegion;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.tipo = tipo;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.estatus = estatus;
	}

	public PromotoresHistorial(String clave, String nombres,
			String apellidoPaterno, String apellidoMaterno,
			Date fechaNacimiento, String calle, String numeroInterior,
			String numeroExterior, int idCodigoPostal, int idRegion,
			int idEstado, int idMunicipio, Integer idLocalidad,
			Integer idSector, String tipo, String telefonoCasa,
			String telefonoOficina, String celular, String correo, String rfc,
			Date fechaAlta, int idUsuario, int estatus, String observaciones,
			Integer meta, Integer comision, Integer tipoEnlace,
			Integer ofiInsDepFac, String carrera, String matricula,
			Integer numeroPersonal, Integer idPromotorpadre, Integer existe,
			Integer replica) {
		this.clave = clave;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.fechaNacimiento = fechaNacimiento;
		this.calle = calle;
		this.numeroInterior = numeroInterior;
		this.numeroExterior = numeroExterior;
		this.idCodigoPostal = idCodigoPostal;
		this.idRegion = idRegion;
		this.idEstado = idEstado;
		this.idMunicipio = idMunicipio;
		this.idLocalidad = idLocalidad;
		this.idSector = idSector;
		this.tipo = tipo;
		this.telefonoCasa = telefonoCasa;
		this.telefonoOficina = telefonoOficina;
		this.celular = celular;
		this.correo = correo;
		this.rfc = rfc;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
		this.estatus = estatus;
		this.observaciones = observaciones;
		this.meta = meta;
		this.comision = comision;
		this.tipoEnlace = tipoEnlace;
		this.ofiInsDepFac = ofiInsDepFac;
		this.carrera = carrera;
		this.matricula = matricula;
		this.numeroPersonal = numeroPersonal;
		this.idPromotorpadre = idPromotorpadre;
		this.existe = existe;
		this.replica = replica;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumeroInterior() {
		return this.numeroInterior;
	}

	public void setNumeroInterior(String numeroInterior) {
		this.numeroInterior = numeroInterior;
	}

	public String getNumeroExterior() {
		return this.numeroExterior;
	}

	public void setNumeroExterior(String numeroExterior) {
		this.numeroExterior = numeroExterior;
	}

	public int getIdCodigoPostal() {
		return this.idCodigoPostal;
	}

	public void setIdCodigoPostal(int idCodigoPostal) {
		this.idCodigoPostal = idCodigoPostal;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Integer getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(Integer idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Integer getIdSector() {
		return this.idSector;
	}

	public void setIdSector(Integer idSector) {
		this.idSector = idSector;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTelefonoCasa() {
		return this.telefonoCasa;
	}

	public void setTelefonoCasa(String telefonoCasa) {
		this.telefonoCasa = telefonoCasa;
	}

	public String getTelefonoOficina() {
		return this.telefonoOficina;
	}

	public void setTelefonoOficina(String telefonoOficina) {
		this.telefonoOficina = telefonoOficina;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getMeta() {
		return this.meta;
	}

	public void setMeta(Integer meta) {
		this.meta = meta;
	}

	public Integer getComision() {
		return this.comision;
	}

	public void setComision(Integer comision) {
		this.comision = comision;
	}

	public Integer getTipoEnlace() {
		return this.tipoEnlace;
	}

	public void setTipoEnlace(Integer tipoEnlace) {
		this.tipoEnlace = tipoEnlace;
	}

	public Integer getOfiInsDepFac() {
		return this.ofiInsDepFac;
	}

	public void setOfiInsDepFac(Integer ofiInsDepFac) {
		this.ofiInsDepFac = ofiInsDepFac;
	}

	public String getCarrera() {
		return this.carrera;
	}

	public void setCarrera(String carrera) {
		this.carrera = carrera;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public Integer getNumeroPersonal() {
		return this.numeroPersonal;
	}

	public void setNumeroPersonal(Integer numeroPersonal) {
		this.numeroPersonal = numeroPersonal;
	}

	public Integer getIdPromotorpadre() {
		return this.idPromotorpadre;
	}

	public void setIdPromotorpadre(Integer idPromotorpadre) {
		this.idPromotorpadre = idPromotorpadre;
	}

	public Integer getExiste() {
		return this.existe;
	}

	public void setExiste(Integer existe) {
		this.existe = existe;
	}

	public Integer getReplica() {
		return this.replica;
	}

	public void setReplica(Integer replica) {
		this.replica = replica;
	}

}
