package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Trfc2fc1bId generated by hbm2java
 */
public class Trfc2fc1bId implements java.io.Serializable {

	private int idFc2;
	private int idFc1b;

	public Trfc2fc1bId() {
	}

	public Trfc2fc1bId(int idFc2, int idFc1b) {
		this.idFc2 = idFc2;
		this.idFc1b = idFc1b;
	}

	public int getIdFc2() {
		return this.idFc2;
	}

	public void setIdFc2(int idFc2) {
		this.idFc2 = idFc2;
	}

	public int getIdFc1b() {
		return this.idFc1b;
	}

	public void setIdFc1b(int idFc1b) {
		this.idFc1b = idFc1b;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Trfc2fc1bId))
			return false;
		Trfc2fc1bId castOther = (Trfc2fc1bId) other;

		return (this.getIdFc2() == castOther.getIdFc2())
				&& (this.getIdFc1b() == castOther.getIdFc1b());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdFc2();
		result = 37 * result + this.getIdFc1b();
		return result;
	}

}
