package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * PromoMarketing generated by hbm2java
 */
public class PromoMarketing implements java.io.Serializable {

	private Integer id;
	private String nombrePromo;
	private int existencias;

	public PromoMarketing() {
	}

	public PromoMarketing(String nombrePromo, int existencias) {
		this.nombrePromo = nombrePromo;
		this.existencias = existencias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombrePromo() {
		return this.nombrePromo;
	}

	public void setNombrePromo(String nombrePromo) {
		this.nombrePromo = nombrePromo;
	}

	public int getExistencias() {
		return this.existencias;
	}

	public void setExistencias(int existencias) {
		this.existencias = existencias;
	}

}
