package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TipoMovimientoKardex generated by hbm2java
 */
public class TipoMovimientoKardex implements java.io.Serializable {

	private Integer id;
	private String movimiento;

	public TipoMovimientoKardex() {
	}

	public TipoMovimientoKardex(String movimiento) {
		this.movimiento = movimiento;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(String movimiento) {
		this.movimiento = movimiento;
	}

}
