package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TiposColaboradores generated by hbm2java
 */
public class TiposColaboradores implements java.io.Serializable {

	private Integer id;
	private String tipo;
	private int tipoSector;

	public TiposColaboradores() {
	}

	public TiposColaboradores(String tipo, int tipoSector) {
		this.tipo = tipo;
		this.tipoSector = tipoSector;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public int getTipoSector() {
		return this.tipoSector;
	}

	public void setTipoSector(int tipoSector) {
		this.tipoSector = tipoSector;
	}

}
