package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Premios generated by hbm2java
 */
public class Premios implements java.io.Serializable {

	private Integer id;
	private int idSorteo;
	private int numeroPremio;
	private String nombre;
	private String descripcionLarga;
	private String descripcionCorta;
	private Double valorUnitario;
	private Integer idPremioAsignado;
	private Integer idGanador;
	private Integer idBoleto;
	private String lugar;
	private String fecha;
	private Integer idTipoIdentificacion;
	private String folio;
	private Integer auto;
	private String serie;
	private String factura;
	private String motor;
	private String descMaterialesImpresos;
	private String numeroCheque;

	public Premios() {
	}

	public Premios(int idSorteo, int numeroPremio, String nombre) {
		this.idSorteo = idSorteo;
		this.numeroPremio = numeroPremio;
		this.nombre = nombre;
	}

	public Premios(int idSorteo, int numeroPremio, String nombre,
			String descripcionLarga, String descripcionCorta,
			Double valorUnitario, Integer idPremioAsignado, Integer idGanador,
			Integer idBoleto, String lugar, String fecha,
			Integer idTipoIdentificacion, String folio, Integer auto,
			String serie, String factura, String motor,
			String descMaterialesImpresos, String numeroCheque) {
		this.idSorteo = idSorteo;
		this.numeroPremio = numeroPremio;
		this.nombre = nombre;
		this.descripcionLarga = descripcionLarga;
		this.descripcionCorta = descripcionCorta;
		this.valorUnitario = valorUnitario;
		this.idPremioAsignado = idPremioAsignado;
		this.idGanador = idGanador;
		this.idBoleto = idBoleto;
		this.lugar = lugar;
		this.fecha = fecha;
		this.idTipoIdentificacion = idTipoIdentificacion;
		this.folio = folio;
		this.auto = auto;
		this.serie = serie;
		this.factura = factura;
		this.motor = motor;
		this.descMaterialesImpresos = descMaterialesImpresos;
		this.numeroCheque = numeroCheque;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdSorteo() {
		return this.idSorteo;
	}

	public void setIdSorteo(int idSorteo) {
		this.idSorteo = idSorteo;
	}

	public int getNumeroPremio() {
		return this.numeroPremio;
	}

	public void setNumeroPremio(int numeroPremio) {
		this.numeroPremio = numeroPremio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcionLarga() {
		return this.descripcionLarga;
	}

	public void setDescripcionLarga(String descripcionLarga) {
		this.descripcionLarga = descripcionLarga;
	}

	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}

	public Double getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(Double valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Integer getIdPremioAsignado() {
		return this.idPremioAsignado;
	}

	public void setIdPremioAsignado(Integer idPremioAsignado) {
		this.idPremioAsignado = idPremioAsignado;
	}

	public Integer getIdGanador() {
		return this.idGanador;
	}

	public void setIdGanador(Integer idGanador) {
		this.idGanador = idGanador;
	}

	public Integer getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(Integer idBoleto) {
		this.idBoleto = idBoleto;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Integer getIdTipoIdentificacion() {
		return this.idTipoIdentificacion;
	}

	public void setIdTipoIdentificacion(Integer idTipoIdentificacion) {
		this.idTipoIdentificacion = idTipoIdentificacion;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public Integer getAuto() {
		return this.auto;
	}

	public void setAuto(Integer auto) {
		this.auto = auto;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public String getDescMaterialesImpresos() {
		return this.descMaterialesImpresos;
	}

	public void setDescMaterialesImpresos(String descMaterialesImpresos) {
		this.descMaterialesImpresos = descMaterialesImpresos;
	}

	public String getNumeroCheque() {
		return this.numeroCheque;
	}

	public void setNumeroCheque(String numeroCheque) {
		this.numeroCheque = numeroCheque;
	}

}
