package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewPromotores generated by hbm2java
 */
public class ViewPromotores implements java.io.Serializable {

	private ViewPromotoresId id;

	public ViewPromotores() {
	}

	public ViewPromotores(ViewPromotoresId id) {
		this.id = id;
	}

	public ViewPromotoresId getId() {
		return this.id;
	}

	public void setId(ViewPromotoresId id) {
		this.id = id;
	}

}
