package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewColaboradores generated by hbm2java
 */
public class ViewColaboradores implements java.io.Serializable {

	private ViewColaboradoresId id;

	public ViewColaboradores() {
	}

	public ViewColaboradores(ViewColaboradoresId id) {
		this.id = id;
	}

	public ViewColaboradoresId getId() {
		return this.id;
	}

	public void setId(ViewColaboradoresId id) {
		this.id = id;
	}

}
