package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Estudiantes2014 generated by hbm2java
 */
public class Estudiantes2014 implements java.io.Serializable {

	private Integer id;
	private String solMatricula;
	private String aspCurp;
	private String aspNombres;
	private String aspApellidopaterno;
	private String aspApellidomaterno;
	private String aspSexo;
	private Date aspFechanacimiento;
	private Integer aspLada;
	private Integer aspTelefono;
	private Long aspCelular;
	private String aspDomicilio;
	private String aspLocalidaddomicilio;
	private String aspMunicipiodomicilio;
	private String estadonacimiento;
	private String carNombreregion;
	private String carNombrearea;
	private String carNombrenivel;
	private String carNombrecarrera;
	private String carModalidad;
	private String carNombrecampus;
	private Integer solLugarcarrera;
	private Integer idSector;
	private int usado;

	public Estudiantes2014() {
	}

	public Estudiantes2014(int usado) {
		this.usado = usado;
	}

	public Estudiantes2014(String solMatricula, String aspCurp,
			String aspNombres, String aspApellidopaterno,
			String aspApellidomaterno, String aspSexo, Date aspFechanacimiento,
			Integer aspLada, Integer aspTelefono, Long aspCelular,
			String aspDomicilio, String aspLocalidaddomicilio,
			String aspMunicipiodomicilio, String estadonacimiento,
			String carNombreregion, String carNombrearea,
			String carNombrenivel, String carNombrecarrera,
			String carModalidad, String carNombrecampus,
			Integer solLugarcarrera, Integer idSector, int usado) {
		this.solMatricula = solMatricula;
		this.aspCurp = aspCurp;
		this.aspNombres = aspNombres;
		this.aspApellidopaterno = aspApellidopaterno;
		this.aspApellidomaterno = aspApellidomaterno;
		this.aspSexo = aspSexo;
		this.aspFechanacimiento = aspFechanacimiento;
		this.aspLada = aspLada;
		this.aspTelefono = aspTelefono;
		this.aspCelular = aspCelular;
		this.aspDomicilio = aspDomicilio;
		this.aspLocalidaddomicilio = aspLocalidaddomicilio;
		this.aspMunicipiodomicilio = aspMunicipiodomicilio;
		this.estadonacimiento = estadonacimiento;
		this.carNombreregion = carNombreregion;
		this.carNombrearea = carNombrearea;
		this.carNombrenivel = carNombrenivel;
		this.carNombrecarrera = carNombrecarrera;
		this.carModalidad = carModalidad;
		this.carNombrecampus = carNombrecampus;
		this.solLugarcarrera = solLugarcarrera;
		this.idSector = idSector;
		this.usado = usado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSolMatricula() {
		return this.solMatricula;
	}

	public void setSolMatricula(String solMatricula) {
		this.solMatricula = solMatricula;
	}

	public String getAspCurp() {
		return this.aspCurp;
	}

	public void setAspCurp(String aspCurp) {
		this.aspCurp = aspCurp;
	}

	public String getAspNombres() {
		return this.aspNombres;
	}

	public void setAspNombres(String aspNombres) {
		this.aspNombres = aspNombres;
	}

	public String getAspApellidopaterno() {
		return this.aspApellidopaterno;
	}

	public void setAspApellidopaterno(String aspApellidopaterno) {
		this.aspApellidopaterno = aspApellidopaterno;
	}

	public String getAspApellidomaterno() {
		return this.aspApellidomaterno;
	}

	public void setAspApellidomaterno(String aspApellidomaterno) {
		this.aspApellidomaterno = aspApellidomaterno;
	}

	public String getAspSexo() {
		return this.aspSexo;
	}

	public void setAspSexo(String aspSexo) {
		this.aspSexo = aspSexo;
	}

	public Date getAspFechanacimiento() {
		return this.aspFechanacimiento;
	}

	public void setAspFechanacimiento(Date aspFechanacimiento) {
		this.aspFechanacimiento = aspFechanacimiento;
	}

	public Integer getAspLada() {
		return this.aspLada;
	}

	public void setAspLada(Integer aspLada) {
		this.aspLada = aspLada;
	}

	public Integer getAspTelefono() {
		return this.aspTelefono;
	}

	public void setAspTelefono(Integer aspTelefono) {
		this.aspTelefono = aspTelefono;
	}

	public Long getAspCelular() {
		return this.aspCelular;
	}

	public void setAspCelular(Long aspCelular) {
		this.aspCelular = aspCelular;
	}

	public String getAspDomicilio() {
		return this.aspDomicilio;
	}

	public void setAspDomicilio(String aspDomicilio) {
		this.aspDomicilio = aspDomicilio;
	}

	public String getAspLocalidaddomicilio() {
		return this.aspLocalidaddomicilio;
	}

	public void setAspLocalidaddomicilio(String aspLocalidaddomicilio) {
		this.aspLocalidaddomicilio = aspLocalidaddomicilio;
	}

	public String getAspMunicipiodomicilio() {
		return this.aspMunicipiodomicilio;
	}

	public void setAspMunicipiodomicilio(String aspMunicipiodomicilio) {
		this.aspMunicipiodomicilio = aspMunicipiodomicilio;
	}

	public String getEstadonacimiento() {
		return this.estadonacimiento;
	}

	public void setEstadonacimiento(String estadonacimiento) {
		this.estadonacimiento = estadonacimiento;
	}

	public String getCarNombreregion() {
		return this.carNombreregion;
	}

	public void setCarNombreregion(String carNombreregion) {
		this.carNombreregion = carNombreregion;
	}

	public String getCarNombrearea() {
		return this.carNombrearea;
	}

	public void setCarNombrearea(String carNombrearea) {
		this.carNombrearea = carNombrearea;
	}

	public String getCarNombrenivel() {
		return this.carNombrenivel;
	}

	public void setCarNombrenivel(String carNombrenivel) {
		this.carNombrenivel = carNombrenivel;
	}

	public String getCarNombrecarrera() {
		return this.carNombrecarrera;
	}

	public void setCarNombrecarrera(String carNombrecarrera) {
		this.carNombrecarrera = carNombrecarrera;
	}

	public String getCarModalidad() {
		return this.carModalidad;
	}

	public void setCarModalidad(String carModalidad) {
		this.carModalidad = carModalidad;
	}

	public String getCarNombrecampus() {
		return this.carNombrecampus;
	}

	public void setCarNombrecampus(String carNombrecampus) {
		this.carNombrecampus = carNombrecampus;
	}

	public Integer getSolLugarcarrera() {
		return this.solLugarcarrera;
	}

	public void setSolLugarcarrera(Integer solLugarcarrera) {
		this.solLugarcarrera = solLugarcarrera;
	}

	public Integer getIdSector() {
		return this.idSector;
	}

	public void setIdSector(Integer idSector) {
		this.idSector = idSector;
	}

	public int getUsado() {
		return this.usado;
	}

	public void setUsado(int usado) {
		this.usado = usado;
	}

}
