package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String usuario;
	private String pass;
	private int idRol;
	private int idEmpleado;
	private Date fechaAlta;
	private int estatus;
	private Integer idSector;

	public Usuarios() {
	}

	public Usuarios(String nombre, String usuario, String pass, int idRol,
			int idEmpleado, Date fechaAlta, int estatus) {
		this.nombre = nombre;
		this.usuario = usuario;
		this.pass = pass;
		this.idRol = idRol;
		this.idEmpleado = idEmpleado;
		this.fechaAlta = fechaAlta;
		this.estatus = estatus;
	}

	public Usuarios(String nombre, String usuario, String pass, int idRol,
			int idEmpleado, Date fechaAlta, int estatus, Integer idSector) {
		this.nombre = nombre;
		this.usuario = usuario;
		this.pass = pass;
		this.idRol = idRol;
		this.idEmpleado = idEmpleado;
		this.fechaAlta = fechaAlta;
		this.estatus = estatus;
		this.idSector = idSector;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	public int getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public Integer getIdSector() {
		return this.idSector;
	}

	public void setIdSector(Integer idSector) {
		this.idSector = idSector;
	}

}
