package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * NominaBoletos generated by hbm2java
 */
public class NominaBoletos implements java.io.Serializable {

	private Integer id;
	private int idComprador;
	private int tipoComprador;
	private int idBoleto;
	private int idNomina;
	private int tabla;
	private int estatus;

	public NominaBoletos() {
	}

	public NominaBoletos(int idComprador, int tipoComprador, int idBoleto,
			int idNomina, int tabla, int estatus) {
		this.idComprador = idComprador;
		this.tipoComprador = tipoComprador;
		this.idBoleto = idBoleto;
		this.idNomina = idNomina;
		this.tabla = tabla;
		this.estatus = estatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdComprador() {
		return this.idComprador;
	}

	public void setIdComprador(int idComprador) {
		this.idComprador = idComprador;
	}

	public int getTipoComprador() {
		return this.tipoComprador;
	}

	public void setTipoComprador(int tipoComprador) {
		this.tipoComprador = tipoComprador;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

	public int getIdNomina() {
		return this.idNomina;
	}

	public void setIdNomina(int idNomina) {
		this.idNomina = idNomina;
	}

	public int getTabla() {
		return this.tabla;
	}

	public void setTabla(int tabla) {
		this.tabla = tabla;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

}
