package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SociedadSinRetornar generated by hbm2java
 */
public class SociedadSinRetornar implements java.io.Serializable {

	private int id;
	private Integer idColaborador;
	private Integer idBoleto;
	private Date fechaAlta;
	private Integer idUsuario;

	public SociedadSinRetornar() {
	}

	public SociedadSinRetornar(int id) {
		this.id = id;
	}

	public SociedadSinRetornar(int id, Integer idColaborador, Integer idBoleto,
			Date fechaAlta, Integer idUsuario) {
		this.id = id;
		this.idColaborador = idColaborador;
		this.idBoleto = idBoleto;
		this.fechaAlta = fechaAlta;
		this.idUsuario = idUsuario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(Integer idColaborador) {
		this.idColaborador = idColaborador;
	}

	public Integer getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(Integer idBoleto) {
		this.idBoleto = idBoleto;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

}
