package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc4b generated by hbm2java
 */
public class Fc4b implements java.io.Serializable {

	private Integer id;
	private int idRetorno;
	private int idBoleto;

	public Fc4b() {
	}

	public Fc4b(int idRetorno, int idBoleto) {
		this.idRetorno = idRetorno;
		this.idBoleto = idBoleto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdRetorno() {
		return this.idRetorno;
	}

	public void setIdRetorno(int idRetorno) {
		this.idRetorno = idRetorno;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

}
