package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Areas generated by hbm2java
 */
public class Areas implements java.io.Serializable {

	private Integer id;
	private String area;

	public Areas() {
	}

	public Areas(String area) {
		this.area = area;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

}
