package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewCompradoresNomina generated by hbm2java
 */
public class ViewCompradoresNomina implements java.io.Serializable {

	private ViewCompradoresNominaId id;

	public ViewCompradoresNomina() {
	}

	public ViewCompradoresNomina(ViewCompradoresNominaId id) {
		this.id = id;
	}

	public ViewCompradoresNominaId getId() {
		return this.id;
	}

	public void setId(ViewCompradoresNominaId id) {
		this.id = id;
	}

}
