package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * BoletosEstudiantes generated by hbm2java
 */
public class BoletosEstudiantes implements java.io.Serializable {

	private Integer id;
	private int idBoleto;
	private String folio;
	private String matricula;
	private String nombre;
	private String telefono;
	private String correo;
	private int estatus;
	private String folioSecuencia;
	private Integer estatusPago;

	public BoletosEstudiantes() {
	}

	public BoletosEstudiantes(int idBoleto, String folio, int estatus) {
		this.idBoleto = idBoleto;
		this.folio = folio;
		this.estatus = estatus;
	}

	public BoletosEstudiantes(int idBoleto, String folio, String matricula,
			String nombre, String telefono, String correo, int estatus,
			String folioSecuencia, Integer estatusPago) {
		this.idBoleto = idBoleto;
		this.folio = folio;
		this.matricula = matricula;
		this.nombre = nombre;
		this.telefono = telefono;
		this.correo = correo;
		this.estatus = estatus;
		this.folioSecuencia = folioSecuencia;
		this.estatusPago = estatusPago;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdBoleto() {
		return this.idBoleto;
	}

	public void setIdBoleto(int idBoleto) {
		this.idBoleto = idBoleto;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getFolioSecuencia() {
		return this.folioSecuencia;
	}

	public void setFolioSecuencia(String folioSecuencia) {
		this.folioSecuencia = folioSecuencia;
	}

	public Integer getEstatusPago() {
		return this.estatusPago;
	}

	public void setEstatusPago(Integer estatusPago) {
		this.estatusPago = estatusPago;
	}

}
