package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * CompradoresBoletos generated by hbm2java
 */
public class CompradoresBoletos implements java.io.Serializable {

	private Integer id;
	private String boleto;
	private String cartera;
	private int idTipoComprador;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String domicilio;
	private String colonia;
	private String codigoPostal;
	private String ciudad;
	private int idEstado;
	private String telefono;
	private String celular;
	private String correo;
	private int sexo;
	private Integer exalumnouv;
	private Date fechaNacimiento;
	private int idSorteo;
	private Integer idUsuario;
	private Date fechaRegistro;

	public CompradoresBoletos() {
	}

	public CompradoresBoletos(String boleto, int idTipoComprador,
			String nombres, int idEstado, int sexo, int idSorteo) {
		this.boleto = boleto;
		this.idTipoComprador = idTipoComprador;
		this.nombres = nombres;
		this.idEstado = idEstado;
		this.sexo = sexo;
		this.idSorteo = idSorteo;
	}

	public CompradoresBoletos(String boleto, String cartera,
			int idTipoComprador, String nombres, String apellidoPaterno,
			String apellidoMaterno, String domicilio, String colonia,
			String codigoPostal, String ciudad, int idEstado, String telefono,
			String celular, String correo, int sexo, Integer exalumnouv,
			Date fechaNacimiento, int idSorteo, Integer idUsuario,
			Date fechaRegistro) {
		this.boleto = boleto;
		this.cartera = cartera;
		this.idTipoComprador = idTipoComprador;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.domicilio = domicilio;
		this.colonia = colonia;
		this.codigoPostal = codigoPostal;
		this.ciudad = ciudad;
		this.idEstado = idEstado;
		this.telefono = telefono;
		this.celular = celular;
		this.correo = correo;
		this.sexo = sexo;
		this.exalumnouv = exalumnouv;
		this.fechaNacimiento = fechaNacimiento;
		this.idSorteo = idSorteo;
		this.idUsuario = idUsuario;
		this.fechaRegistro = fechaRegistro;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBoleto() {
		return this.boleto;
	}

	public void setBoleto(String boleto) {
		this.boleto = boleto;
	}

	public String getCartera() {
		return this.cartera;
	}

	public void setCartera(String cartera) {
		this.cartera = cartera;
	}

	public int getIdTipoComprador() {
		return this.idTipoComprador;
	}

	public void setIdTipoComprador(int idTipoComprador) {
		this.idTipoComprador = idTipoComprador;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public int getSexo() {
		return this.sexo;
	}

	public void setSexo(int sexo) {
		this.sexo = sexo;
	}

	public Integer getExalumnouv() {
		return this.exalumnouv;
	}

	public void setExalumnouv(Integer exalumnouv) {
		this.exalumnouv = exalumnouv;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public int getIdSorteo() {
		return this.idSorteo;
	}

	public void setIdSorteo(int idSorteo) {
		this.idSorteo = idSorteo;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

}
