package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * TiposIncidencias generated by hbm2java
 */
public class TiposIncidencias implements java.io.Serializable {

	private Integer id;
	private String tipo;

	public TiposIncidencias() {
	}

	public TiposIncidencias(String tipo) {
		this.tipo = tipo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
