package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Almacen generated by hbm2java
 */
public class Almacen implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int tipo;
	private int idPromotor;
	private int idColaborador;
	private int idAlianzaPuntoFijo;

	public Almacen() {
	}

	public Almacen(String nombre, int tipo, int idPromotor, int idColaborador,
			int idAlianzaPuntoFijo) {
		this.nombre = nombre;
		this.tipo = tipo;
		this.idPromotor = idPromotor;
		this.idColaborador = idColaborador;
		this.idAlianzaPuntoFijo = idAlianzaPuntoFijo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public int getIdPromotor() {
		return this.idPromotor;
	}

	public void setIdPromotor(int idPromotor) {
		this.idPromotor = idPromotor;
	}

	public int getIdColaborador() {
		return this.idColaborador;
	}

	public void setIdColaborador(int idColaborador) {
		this.idColaborador = idColaborador;
	}

	public int getIdAlianzaPuntoFijo() {
		return this.idAlianzaPuntoFijo;
	}

	public void setIdAlianzaPuntoFijo(int idAlianzaPuntoFijo) {
		this.idAlianzaPuntoFijo = idAlianzaPuntoFijo;
	}

}
