package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Recibos generated by hbm2java
 */
public class Recibos implements java.io.Serializable {

	private Integer id;
	private int idPremio;
	private String lugar;
	private String fecha;
	private String serie;
	private String motor;
	private String circulacion;
	private String factura;
	private int idTipoIdentificacion;
	private String folio;

	public Recibos() {
	}

	public Recibos(int idPremio, String lugar, String fecha,
			int idTipoIdentificacion, String folio) {
		this.idPremio = idPremio;
		this.lugar = lugar;
		this.fecha = fecha;
		this.idTipoIdentificacion = idTipoIdentificacion;
		this.folio = folio;
	}

	public Recibos(int idPremio, String lugar, String fecha, String serie,
			String motor, String circulacion, String factura,
			int idTipoIdentificacion, String folio) {
		this.idPremio = idPremio;
		this.lugar = lugar;
		this.fecha = fecha;
		this.serie = serie;
		this.motor = motor;
		this.circulacion = circulacion;
		this.factura = factura;
		this.idTipoIdentificacion = idTipoIdentificacion;
		this.folio = folio;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdPremio() {
		return this.idPremio;
	}

	public void setIdPremio(int idPremio) {
		this.idPremio = idPremio;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public String getCirculacion() {
		return this.circulacion;
	}

	public void setCirculacion(String circulacion) {
		this.circulacion = circulacion;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public int getIdTipoIdentificacion() {
		return this.idTipoIdentificacion;
	}

	public void setIdTipoIdentificacion(int idTipoIdentificacion) {
		this.idTipoIdentificacion = idTipoIdentificacion;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

}
