package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * SorteoColaboradoresHistorial generated by hbm2java
 */
public class SorteoColaboradoresHistorial implements java.io.Serializable {

	private SorteoColaboradoresHistorialId id;

	public SorteoColaboradoresHistorial() {
	}

	public SorteoColaboradoresHistorial(SorteoColaboradoresHistorialId id) {
		this.id = id;
	}

	public SorteoColaboradoresHistorialId getId() {
		return this.id;
	}

	public void setId(SorteoColaboradoresHistorialId id) {
		this.id = id;
	}

}
