package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Boletos generated by hbm2java
 */
public class Boletos implements java.io.Serializable {

	private Integer id;
	private String folio;
	private int idCartera;
	private boolean estado;
	private Integer idTipoIncidencia;
	private int asignado;

	public Boletos() {
	}

	public Boletos(String folio, int idCartera, boolean estado, int asignado) {
		this.folio = folio;
		this.idCartera = idCartera;
		this.estado = estado;
		this.asignado = asignado;
	}

	public Boletos(String folio, int idCartera, boolean estado,
			Integer idTipoIncidencia, int asignado) {
		this.folio = folio;
		this.idCartera = idCartera;
		this.estado = estado;
		this.idTipoIncidencia = idTipoIncidencia;
		this.asignado = asignado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

	public int getIdCartera() {
		return this.idCartera;
	}

	public void setIdCartera(int idCartera) {
		this.idCartera = idCartera;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Integer getIdTipoIncidencia() {
		return this.idTipoIncidencia;
	}

	public void setIdTipoIncidencia(Integer idTipoIncidencia) {
		this.idTipoIncidencia = idTipoIncidencia;
	}

	public int getAsignado() {
		return this.asignado;
	}

	public void setAsignado(int asignado) {
		this.asignado = asignado;
	}

}
