package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Localidades generated by hbm2java
 */
public class Localidades implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int idMunicipio;

	public Localidades() {
	}

	public Localidades(String nombre, int idMunicipio) {
		this.nombre = nombre;
		this.idMunicipio = idMunicipio;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(int idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

}
