package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * ViewPromotoresHistorial generated by hbm2java
 */
public class ViewPromotoresHistorial implements java.io.Serializable {

	private ViewPromotoresHistorialId id;

	public ViewPromotoresHistorial() {
	}

	public ViewPromotoresHistorial(ViewPromotoresHistorialId id) {
		this.id = id;
	}

	public ViewPromotoresHistorialId getId() {
		return this.id;
	}

	public void setId(ViewPromotoresHistorialId id) {
		this.id = id;
	}

}
