package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * PagosAcumulados generated by hbm2java
 */
public class PagosAcumulados implements java.io.Serializable {

	private Integer id;
	private int idPago;
	private Integer idTraspaso;
	private int montoAcumulado;
	private int idResponsable;
	private int idUsuario;

	public PagosAcumulados() {
	}

	public PagosAcumulados(int idPago, int montoAcumulado, int idResponsable,
			int idUsuario) {
		this.idPago = idPago;
		this.montoAcumulado = montoAcumulado;
		this.idResponsable = idResponsable;
		this.idUsuario = idUsuario;
	}

	public PagosAcumulados(int idPago, Integer idTraspaso, int montoAcumulado,
			int idResponsable, int idUsuario) {
		this.idPago = idPago;
		this.idTraspaso = idTraspaso;
		this.montoAcumulado = montoAcumulado;
		this.idResponsable = idResponsable;
		this.idUsuario = idUsuario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdPago() {
		return this.idPago;
	}

	public void setIdPago(int idPago) {
		this.idPago = idPago;
	}

	public Integer getIdTraspaso() {
		return this.idTraspaso;
	}

	public void setIdTraspaso(Integer idTraspaso) {
		this.idTraspaso = idTraspaso;
	}

	public int getMontoAcumulado() {
		return this.montoAcumulado;
	}

	public void setMontoAcumulado(int montoAcumulado) {
		this.montoAcumulado = montoAcumulado;
	}

	public int getIdResponsable() {
		return this.idResponsable;
	}

	public void setIdResponsable(int idResponsable) {
		this.idResponsable = idResponsable;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

}
