package Pojos;

// Generated Feb 15, 2016 4:42:55 PM by Hibernate Tools 4.0.0

/**
 * Fc4 generated by hbm2java
 */
public class Fc4 implements java.io.Serializable {

	private Integer id;
	private int idRetorno;
	private int idCartera;

	public Fc4() {
	}

	public Fc4(int idRetorno, int idCartera) {
		this.idRetorno = idRetorno;
		this.idCartera = idCartera;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdRetorno() {
		return this.idRetorno;
	}

	public void setIdRetorno(int idRetorno) {
		this.idRetorno = idRetorno;
	}

	public int getIdCartera() {
		return this.idCartera;
	}

	public void setIdCartera(int idCartera) {
		this.idCartera = idCartera;
	}

}
